package escuela.cobranza.service.impl;

import escuela.alumno.entity.Alumno;import escuela.cobranza.dto.request.AjusteCargoRequest;import escuela.cobranza.entity.*;import escuela.cobranza.mapper.AjusteCargoMapper;import escuela.cobranza.repository.*;import escuela.common.exception.ReglaNegocioException;import escuela.inscripcion.entity.Inscripcion;import escuela.institucion.entity.*;import escuela.seguridad.repository.UsuarioRepository;
import org.junit.jupiter.api.Test;import java.math.BigDecimal;import java.time.LocalDate;import java.util.Optional;
import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.any;import static org.mockito.Mockito.*;

class AjusteCargoServiceImplTest {
 private final AjusteCargoRepository repository=mock(AjusteCargoRepository.class);private final CargoRepository cargos=mock(CargoRepository.class);
 private final AjusteCargoServiceImpl service=new AjusteCargoServiceImpl(repository,cargos,mock(UsuarioRepository.class),new AjusteCargoMapper());
 @Test void rechazaDescuentoQueDejaTotalNegativo(){Cargo c=cargo();when(cargos.findByIdForUpdate(3L)).thenReturn(Optional.of(c));var r=new AjusteCargoRequest(3L,TipoAjusteCargo.DESCUENTO,EfectoAjusteCargo.DISMINUCION,new BigDecimal("1000.01"),"Convenio",LocalDate.now());assertThatThrownBy(()->service.crear(r)).isInstanceOf(ReglaNegocioException.class).hasMessageContaining("debajo de cero");}
 @Test void respetaPoliticaDelConcepto(){Cargo c=cargo();c.getConceptoCobro().setPermiteRecargo(false);when(cargos.findByIdForUpdate(3L)).thenReturn(Optional.of(c));var r=new AjusteCargoRequest(3L,TipoAjusteCargo.RECARGO,EfectoAjusteCargo.AUMENTO,new BigDecimal("10.00"),"Mora",LocalDate.now());assertThatThrownBy(()->service.crear(r)).isInstanceOf(ReglaNegocioException.class).hasMessageContaining("no permite recargos");}
 @Test void reversaConEfectoOpuestoYConservaOriginal(){Cargo c=cargo();AjusteCargo original=new AjusteCargo();original.setId(8L);original.setVersion(0L);original.setCargo(c);original.setTipo(TipoAjusteCargo.DESCUENTO);original.setEfecto(EfectoAjusteCargo.DISMINUCION);original.setMonto(new BigDecimal("100.00"));original.setMotivo("Pronto pago");original.setFechaEfectiva(LocalDate.now());when(repository.findByIdForUpdate(8L)).thenReturn(Optional.of(original));when(repository.saveAndFlush(any())).thenAnswer(a->{AjusteCargo x=a.getArgument(0);x.setId(9L);x.setVersion(0L);return x;});var respuesta=service.reversar(8L,0L,"Captura incorrecta");assertThat(respuesta.efecto()).isEqualTo(EfectoAjusteCargo.AUMENTO);assertThat(respuesta.reversaDeId()).isEqualTo(8L);verify(repository).saveAndFlush(any());}
 private Cargo cargo(){Institucion inst=new Institucion();inst.setId(1L);Alumno alumno=new Alumno();alumno.setId(4L);alumno.setInstitucion(inst);alumno.setMatricula("A-1");alumno.setNombres("Ana");alumno.setPrimerApellido("López");Plantel p=new Plantel();p.setId(2L);p.setNombre("Centro");p.setInstitucion(inst);Inscripcion i=new Inscripcion();i.setId(5L);i.setAlumno(alumno);i.setPlantel(p);ConceptoCobro concepto=new ConceptoCobro();concepto.setId(6L);concepto.setNombre("Colegiatura");concepto.setPermiteDescuento(true);concepto.setPermiteRecargo(true);Cargo c=new Cargo();c.setId(3L);c.setVersion(0L);c.setInscripcion(i);c.setConceptoCobro(concepto);c.setImporteOriginal(new BigDecimal("1000.00"));c.setMoneda("MXN");c.setEstadoRegistro(EstadoRegistroCargo.EMITIDO);return c;}
}
