package escuela.admin.controller;
import escuela.admin.dto.*;import escuela.admin.support.MensajeErrorFormulario;import escuela.cobranza.entity.*;import escuela.cobranza.service.*;import escuela.common.exception.ReglaNegocioException;import escuela.seguridad.service.AlcanceDatosService;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.orm.ObjectOptimisticLockingFailureException;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.validation.BindingResult;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller @RequiredArgsConstructor @RequestMapping("/admin/ajustes-cargo") public class AjusteCargoAdminController {
 private final AjusteCargoService service;private final CargoService cargoService;private final AlcanceDatosService alcance;
 @GetMapping("/{id}/editar") String detalle(@PathVariable Long id,Model m){alcance.validarRecurso(ModuloCatalogo.AJUSTES_CARGO,id);m.addAttribute("ajuste",service.obtener(id));return "admin/ajuste-cargo-detalle";}
 @PostMapping("/{id}/reversar") String reversar(@PathVariable Long id,@RequestParam Long version,@RequestParam String motivo,Model m,RedirectAttributes flash){alcance.validarRecurso(ModuloCatalogo.AJUSTES_CARGO,id);try{service.reversar(id,version,motivo);}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){m.addAttribute("ajuste",service.obtener(id));m.addAttribute("motivoCapturado",motivo);m.addAttribute("errorOperacion",MensajeErrorFormulario.desde(x));return "admin/ajuste-cargo-detalle";}flash.addFlashAttribute("mensaje","Ajuste reversado; ambos movimientos permanecen en el historial");return "redirect:/admin/catalogos/ajustes-cargo";}
 @PostMapping("/cargo/{cargoId}") String crear(@PathVariable Long cargoId,@Valid @ModelAttribute("ajusteForm") AjusteCargoForm f,BindingResult e,Model m,RedirectAttributes flash){alcance.validarRecurso(ModuloCatalogo.CARGOS,cargoId);if(e.hasErrors()){prepararCargo(m,cargoId,f);return "admin/cargo-detalle";}try{service.crear(f.request(cargoId));}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){prepararCargo(m,cargoId,f);m.addAttribute("errorAjuste",MensajeErrorFormulario.desde(x));return "admin/cargo-detalle";}flash.addFlashAttribute("mensaje","Ajuste aplicado correctamente");return "redirect:/admin/cargos/"+cargoId+"/editar";}
 public void prepararCargo(Model m,Long cargoId,AjusteCargoForm f){m.addAttribute("cargo",cargoService.obtener(cargoId));m.addAttribute("ajustes",service.listarPorCargo(cargoId));m.addAttribute("ajusteForm",f);m.addAttribute("tiposAjuste",new TipoAjusteCargo[]{TipoAjusteCargo.DESCUENTO,TipoAjusteCargo.RECARGO,TipoAjusteCargo.CORRECCION});m.addAttribute("efectosAjuste",EfectoAjusteCargo.values());}
}
