package escuela.admin.controller;
import escuela.admin.dto.*;import escuela.admin.support.MensajeErrorFormulario;import escuela.cobranza.entity.*;import escuela.cobranza.service.*;import escuela.common.exception.ReglaNegocioException;import escuela.inscripcion.service.InscripcionService;import escuela.institucion.dto.response.*;import escuela.institucion.service.*;import escuela.seguridad.service.AlcanceDatosService;
import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.orm.ObjectOptimisticLockingFailureException;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.validation.BindingResult;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.support.RedirectAttributes;import java.util.List;
@Controller @RequiredArgsConstructor @RequestMapping("/admin/becas-alumno") public class BecaAlumnoAdminController {
 private final BecaAlumnoService service;private final InscripcionService inscripcionService;private final ConceptoCobroService conceptoService;private final TipoBecaService tipoService;private final InstitucionService institucionService;private final PlantelService plantelService;private final AlcanceDatosService alcance;
 @GetMapping("/nuevo") String nuevo(Model m){preparar(m,new BecaAlumnoForm(),null);return "admin/beca-alumno-form";}
 @PostMapping String crear(@Valid @ModelAttribute("form") BecaAlumnoForm f,BindingResult e,Model m,RedirectAttributes flash){validar(f,e);if(e.hasErrors()){preparar(m,f,null);return "admin/beca-alumno-form";}try{service.crear(f.request());}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){error(m,f,null,x);return "admin/beca-alumno-form";}flash.addFlashAttribute("mensaje","Beca individual asignada; se aplicará únicamente a cargos futuros");return "redirect:/admin/catalogos/becas-alumno";}
 @GetMapping("/{id}/editar") String editar(@PathVariable Long id,Model m){alcance.validarRecurso(ModuloCatalogo.BECAS_ALUMNO,id);preparar(m,BecaAlumnoForm.desde(service.obtener(id)),id);return "admin/beca-alumno-form";}
 @PostMapping("/{id}") String actualizar(@PathVariable Long id,@Valid @ModelAttribute("form") BecaAlumnoForm f,BindingResult e,Model m,RedirectAttributes flash){alcance.validarRecurso(ModuloCatalogo.BECAS_ALUMNO,id);validar(f,e);if(e.hasErrors()){preparar(m,f,id);return "admin/beca-alumno-form";}try{service.actualizar(id,f.request());}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){error(m,f,id,x);return "admin/beca-alumno-form";}flash.addFlashAttribute("mensaje","Beca actualizada; los cargos emitidos conservaron su importe histórico");return "redirect:/admin/catalogos/becas-alumno";}
 private void preparar(Model m,BecaAlumnoForm f,Long id){List<InstitucionResponse> ins=alcance.filtrarInstituciones(institucionService.listar());List<PlantelResponse> ps=alcance.filtrarPlanteles(plantelService.listar());if(f.getInstitucionId()==null&&ins.size()==1)f.setInstitucionId(ins.getFirst().id());if(f.getPlantelId()==null&&ps.size()==1)f.setPlantelId(ps.getFirst().id());if((f.getMoneda()==null||f.getMoneda().isBlank())&&f.getInstitucionId()!=null)ins.stream().filter(i->i.id().equals(f.getInstitucionId())).findFirst().map(InstitucionResponse::monedaPredeterminada).ifPresent(f::setMoneda);m.addAttribute("form",f);m.addAttribute("id",id);m.addAttribute("edicion",id!=null);m.addAttribute("instituciones",ins);m.addAttribute("planteles",ps);m.addAttribute("modalidades",ModalidadBeca.values());m.addAttribute("estados",EstadoBeca.values());m.addAttribute("inscripcionSeleccionada",etiquetaInscripcion(f.getInscripcionId()));m.addAttribute("conceptoSeleccionado",etiquetaConcepto(f.getConceptoCobroId()));m.addAttribute("tipoSeleccionado",etiquetaTipo(f.getTipoBecaId()));}
 private void validar(BecaAlumnoForm f,BindingResult e){if(f.getInstitucionId()!=null)alcance.validarInstitucion(f.getInstitucionId());if(f.getPlantelId()!=null)alcance.validarPlantel(f.getPlantelId());if(f.getInscripcionId()!=null)alcance.validarRecurso(ModuloCatalogo.INSCRIPCIONES,f.getInscripcionId());if(f.getConceptoCobroId()!=null)alcance.validarRecurso(ModuloCatalogo.CONCEPTOS_COBRO,f.getConceptoCobroId());if(f.getTipoBecaId()!=null)alcance.validarRecurso(ModuloCatalogo.TIPOS_BECA,f.getTipoBecaId());if(f.getInstitucionId()==null||f.getPlantelId()==null)return;if(f.getInscripcionId()!=null){var i=inscripcionService.obtener(f.getInscripcionId());if(!i.institucionId().equals(f.getInstitucionId()))e.rejectValue("inscripcionId","beca.institucion","La inscripción no pertenece a la institución indicada");if(!i.plantelId().equals(f.getPlantelId()))e.rejectValue("inscripcionId","beca.plantel","La inscripción no pertenece al plantel indicado");}if(f.getConceptoCobroId()!=null&&!conceptoService.obtener(f.getConceptoCobroId()).institucionId().equals(f.getInstitucionId()))e.rejectValue("conceptoCobroId","beca.concepto","El concepto no pertenece a la institución indicada");if(f.getTipoBecaId()!=null&&!tipoService.obtener(f.getTipoBecaId()).institucionId().equals(f.getInstitucionId()))e.rejectValue("tipoBecaId","beca.tipo","El tipo de beca no pertenece a la institución indicada");}
 private String etiquetaInscripcion(Long id){if(id==null)return "";var i=inscripcionService.obtener(id);return i.numeroInscripcion()+" · "+i.alumnoNombre();}private String etiquetaConcepto(Long id){if(id==null)return "";var c=conceptoService.obtener(id);return c.codigo()+" · "+c.nombre();}private String etiquetaTipo(Long id){if(id==null)return "";var t=tipoService.obtener(id);return t.codigo()+" · "+t.nombre();}private void error(Model m,BecaAlumnoForm f,Long id,RuntimeException x){preparar(m,f,id);m.addAttribute("errorOperacion",MensajeErrorFormulario.desde(x));}
}
