package escuela.admin.controller;
import escuela.admin.dto.*;import escuela.admin.support.MensajeErrorFormulario;import escuela.cobranza.entity.*;import escuela.cobranza.service.*;import escuela.common.exception.ReglaNegocioException;import escuela.institucion.dto.response.*;import escuela.institucion.service.*;import escuela.seguridad.service.AlcanceDatosService;import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.orm.ObjectOptimisticLockingFailureException;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.validation.BindingResult;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.support.RedirectAttributes;import java.util.List;
@Controller @RequiredArgsConstructor @RequestMapping("/admin/politicas-recargo")public class PoliticaRecargoAdminController{
 private final PoliticaRecargoService service;private final ConceptoCobroService conceptoService;private final InstitucionService institucionService;private final PlantelService plantelService;private final AlcanceDatosService alcance;
 @GetMapping("/nuevo")String nuevo(Model m){preparar(m,new PoliticaRecargoForm(),null);return"admin/politica-recargo-form";}
 @PostMapping String crear(@Valid @ModelAttribute("form")PoliticaRecargoForm f,BindingResult e,Model m,RedirectAttributes flash){validar(f,e);if(e.hasErrors()){preparar(m,f,null);return"admin/politica-recargo-form";}try{service.crear(f.request());}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){error(m,f,null,x);return"admin/politica-recargo-form";}flash.addFlashAttribute("mensaje","Política de recargo creada correctamente");return"redirect:/admin/catalogos/politicas-recargo";}
 @GetMapping("/{id}/editar")String editar(@PathVariable Long id,Model m){alcance.validarRecurso(ModuloCatalogo.POLITICAS_RECARGO,id);preparar(m,PoliticaRecargoForm.desde(service.obtener(id)),id);return"admin/politica-recargo-form";}
 @PostMapping("/{id}")String actualizar(@PathVariable Long id,@Valid @ModelAttribute("form")PoliticaRecargoForm f,BindingResult e,Model m,RedirectAttributes flash){alcance.validarRecurso(ModuloCatalogo.POLITICAS_RECARGO,id);validar(f,e);if(e.hasErrors()){preparar(m,f,id);return"admin/politica-recargo-form";}try{service.actualizar(id,f.request());}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){error(m,f,id,x);return"admin/politica-recargo-form";}flash.addFlashAttribute("mensaje","Política actualizada; los recargos emitidos conservaron sus valores históricos");return"redirect:/admin/catalogos/politicas-recargo";}
 @PostMapping("/{id}/desactivar")String desactivar(@PathVariable Long id,@RequestParam Long version,RedirectAttributes flash){alcance.validarRecurso(ModuloCatalogo.POLITICAS_RECARGO,id);service.desactivar(id,version);flash.addFlashAttribute("mensaje","Política de recargo desactivada");return"redirect:/admin/catalogos/politicas-recargo";}
 @GetMapping("/generar")String generador(Model m){prepararGenerador(m,new GeneracionRecargosForm());return"admin/recargo-generar";}
 @PostMapping("/generar")String generar(@Valid @ModelAttribute("form")GeneracionRecargosForm f,BindingResult e,Model m,RedirectAttributes flash){validarGenerador(f,e);if(e.hasErrors()){prepararGenerador(m,f);return"admin/recargo-generar";}try{var r=service.generar(f.request());flash.addFlashAttribute("mensaje","Recargos: "+r.recargosGenerados()+" nuevos, "+r.recargosExistentes()+" existentes; "+r.cargosRevisados()+" cargos revisados");}catch(ReglaNegocioException|DataIntegrityViolationException x){prepararGenerador(m,f);m.addAttribute("errorOperacion",MensajeErrorFormulario.desde(x));return"admin/recargo-generar";}return"redirect:/admin/catalogos/ajustes-cargo";}
 private void preparar(Model m,PoliticaRecargoForm f,Long id){var ins=alcance.filtrarInstituciones(institucionService.listar());if(f.getInstitucionId()==null&&ins.size()==1)f.setInstitucionId(ins.getFirst().id());if((f.getMoneda()==null||f.getMoneda().isBlank())&&f.getInstitucionId()!=null)ins.stream().filter(i->i.id().equals(f.getInstitucionId())).findFirst().map(InstitucionResponse::monedaPredeterminada).ifPresent(f::setMoneda);m.addAttribute("form",f);m.addAttribute("id",id);m.addAttribute("edicion",id!=null);m.addAttribute("instituciones",ins);m.addAttribute("modalidades",ModalidadBeca.values());m.addAttribute("periodicidades",PeriodicidadRecargo.values());m.addAttribute("tiposLimite",TipoLimiteRecargo.values());m.addAttribute("conceptoSeleccionado",etiqueta(f.getConceptoCobroId()));}
 private void validar(PoliticaRecargoForm f,BindingResult e){if(f.getInstitucionId()!=null)alcance.validarAdministracionInstitucional(f.getInstitucionId());if(f.getConceptoCobroId()!=null){alcance.validarRecurso(ModuloCatalogo.CONCEPTOS_COBRO,f.getConceptoCobroId());if(f.getInstitucionId()!=null&&!conceptoService.obtener(f.getConceptoCobroId()).institucionId().equals(f.getInstitucionId()))e.rejectValue("conceptoCobroId","politica.concepto","El concepto no pertenece a la institución indicada");}}
 private void prepararGenerador(Model m,GeneracionRecargosForm f){List<InstitucionResponse> ins=alcance.filtrarInstituciones(institucionService.listar());List<PlantelResponse> ps=alcance.filtrarPlanteles(plantelService.listar());if(f.getInstitucionId()==null&&ins.size()==1)f.setInstitucionId(ins.getFirst().id());m.addAttribute("form",f);m.addAttribute("instituciones",ins);m.addAttribute("planteles",ps);}
 private void validarGenerador(GeneracionRecargosForm f,BindingResult e){if(f.getInstitucionId()!=null)alcance.validarInstitucion(f.getInstitucionId());if(f.getPlantelId()==null){if(f.getInstitucionId()!=null)alcance.validarAdministracionInstitucional(f.getInstitucionId());return;}alcance.validarPlantel(f.getPlantelId());if(f.getInstitucionId()!=null&&!plantelService.obtener(f.getPlantelId()).institucionId().equals(f.getInstitucionId()))e.rejectValue("plantelId","recargo.plantel","El plantel no pertenece a la institución indicada");}
 private String etiqueta(Long id){if(id==null)return"";var c=conceptoService.obtener(id);return c.codigo()+" · "+c.nombre();}private void error(Model m,PoliticaRecargoForm f,Long id,RuntimeException x){preparar(m,f,id);m.addAttribute("errorOperacion",MensajeErrorFormulario.desde(x));}
}
