package escuela.admin.controller;
import escuela.admin.dto.*;import escuela.admin.support.MensajeErrorFormulario;import escuela.cobranza.dto.response.TipoBecaResponse;import escuela.cobranza.service.TipoBecaService;import escuela.common.exception.ReglaNegocioException;import escuela.institucion.service.InstitucionService;import escuela.seguridad.service.AlcanceDatosService;
import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.springframework.dao.DataIntegrityViolationException;import org.springframework.orm.ObjectOptimisticLockingFailureException;import org.springframework.stereotype.Controller;import org.springframework.ui.Model;import org.springframework.validation.BindingResult;import org.springframework.web.bind.annotation.*;import org.springframework.web.servlet.mvc.support.RedirectAttributes;
@Controller @RequiredArgsConstructor @RequestMapping("/admin/tipos-beca") public class TipoBecaAdminController {
 private final TipoBecaService service;private final InstitucionService institucionService;private final AlcanceDatosService alcance;
 @GetMapping("/nuevo") String nuevo(Model m){preparar(m,new TipoBecaForm(),null);return "admin/tipo-beca-form";}
 @PostMapping String crear(@Valid @ModelAttribute("form") TipoBecaForm f,BindingResult e,Model m,RedirectAttributes flash){validar(f);if(e.hasErrors()){preparar(m,f,null);return "admin/tipo-beca-form";}try{service.crear(f.request());}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){error(m,f,null,x);return "admin/tipo-beca-form";}flash.addFlashAttribute("mensaje","Tipo de beca creado correctamente");return "redirect:/admin/catalogos/tipos-beca";}
 @GetMapping("/{id}/editar") String editar(@PathVariable Long id,Model m){alcance.validarRecurso(ModuloCatalogo.TIPOS_BECA,id);TipoBecaResponse r=service.obtener(id);alcance.validarAdministracionInstitucional(r.institucionId());preparar(m,TipoBecaForm.desde(r),id);return "admin/tipo-beca-form";}
 @PostMapping("/{id}") String actualizar(@PathVariable Long id,@Valid @ModelAttribute("form") TipoBecaForm f,BindingResult e,Model m,RedirectAttributes flash){alcance.validarRecurso(ModuloCatalogo.TIPOS_BECA,id);validar(f);if(e.hasErrors()){preparar(m,f,id);return "admin/tipo-beca-form";}try{service.actualizar(id,f.request());}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){error(m,f,id,x);return "admin/tipo-beca-form";}flash.addFlashAttribute("mensaje","Tipo de beca actualizado correctamente");return "redirect:/admin/catalogos/tipos-beca";}
 @PostMapping("/{id}/desactivar") String desactivar(@PathVariable Long id,@RequestParam Long version,Model m,RedirectAttributes flash){alcance.validarRecurso(ModuloCatalogo.TIPOS_BECA,id);try{service.desactivar(id,version);}catch(ReglaNegocioException|DataIntegrityViolationException|ObjectOptimisticLockingFailureException x){TipoBecaResponse r=service.obtener(id);error(m,TipoBecaForm.desde(r),id,x);return "admin/tipo-beca-form";}flash.addFlashAttribute("mensaje","Tipo de beca desactivado correctamente");return "redirect:/admin/catalogos/tipos-beca";}
 private void preparar(Model m,TipoBecaForm f,Long id){var ins=alcance.filtrarInstituciones(institucionService.listar());if(f.getInstitucionId()==null&&ins.size()==1)f.setInstitucionId(ins.getFirst().id());m.addAttribute("form",f);m.addAttribute("id",id);m.addAttribute("edicion",id!=null);m.addAttribute("instituciones",ins);}
 private void validar(TipoBecaForm f){if(f.getInstitucionId()!=null)alcance.validarAdministracionInstitucional(f.getInstitucionId());}
 private void error(Model m,TipoBecaForm f,Long id,RuntimeException x){preparar(m,f,id);m.addAttribute("errorOperacion",MensajeErrorFormulario.desde(x));}
}
