package escuela.compras.service;

import escuela.compras.dto.*;
import escuela.compras.entity.*;
import escuela.compras.repository.*;
import escuela.common.exception.*;
import escuela.finanzas.dto.request.*;
import escuela.finanzas.entity.*;
import escuela.finanzas.repository.*;
import escuela.finanzas.service.*;
import escuela.institucion.entity.*;
import escuela.institucion.repository.*;
import escuela.seguridad.repository.UsuarioRepository;
import escuela.seguridad.service.*;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*;
import org.springframework.data.jpa.domain.Specification;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.math.*;
import java.time.*;
import java.util.*;
import static escuela.common.mapper.NormalizacionTexto.limpiar;
import static escuela.common.service.ValidacionVersion.verificar;

@Service @RequiredArgsConstructor @Transactional
public class CompraService {
    private final CompraRepository compras;private final ProveedorRepository proveedores;private final InstitucionRepository instituciones;
    private final PlantelRepository planteles;private final CuentaFinancieraRepository cuentas;private final MotivoFinancieroRepository motivos;
    private final MovimientoFinancieroRepository movimientosRepo;private final ReversionFinancieraRepository reversiones;
    private final UsuarioRepository usuarios;private final MovimientoManualService movimientos;private final ReversionFinancieraService reversor;private final AlcanceDatosService alcance;

    public Long crear(CompraForm f){Contexto c=validar(f,null);Compra x=new Compra();x.setInstitucion(c.institucion());x.setFolio("TEMP-"+UUID.randomUUID());copiar(x,f,c);x=compras.saveAndFlush(x);x.setFolio("COM-"+String.format("%08d",x.getId()));return compras.saveAndFlush(x).getId();}
    public void actualizar(Long id,CompraForm f){Compra x=bloquear(id);validarAcceso(x);verificar(x,f.getVersion(),"Compra");if(x.getEstado()!=EstadoCompra.BORRADOR)throw new ReglaNegocioException("Sólo una compra en borrador puede editarse");if(!x.getInstitucion().getId().equals(f.getInstitucionId()))throw new ReglaNegocioException("No se puede cambiar la institución de la compra");Contexto c=validar(f,id);copiar(x,f,c);compras.saveAndFlush(x);}
    public void confirmar(Long id,Long version,UsuarioPrincipal principal){Compra x=bloquear(id);validarAcceso(x);verificar(x,version,"Compra");if(x.getEstado()!=EstadoCompra.BORRADOR)throw new ReglaNegocioException("La compra ya no está en borrador");if(x.getPartidas().isEmpty())throw new ReglaNegocioException("La compra no tiene partidas");ZoneId z=ZoneId.of(x.getInstitucion().getZonaHoraria());var respuesta=movimientos.registrar(new MovimientoManualRequest(x.getInstitucion().getId(),x.getCuenta().getId(),x.getPlantel()==null?null:x.getPlantel().getId(),LocalDateTime.ofInstant(x.getFechaOperacion(),z),DireccionMovimiento.EGRESO,x.getMotivoFinanciero().getId(),x.getTotal(),"Compra "+x.getFolio()+" · "+x.getProveedor().getRazonSocial(),x.getDocumentoReferencia(),x.getProveedor().getRazonSocial(),"COMPRA:"+x.getId()));x.setMovimientoEgreso(movimientosRepo.findById(respuesta.id()).orElseThrow());x.setEstado(EstadoCompra.CONFIRMADA);compras.saveAndFlush(x);}
    public void cancelar(Long id,CancelarCompraForm f,UsuarioPrincipal principal){Compra x=bloquear(id);validarAcceso(x);verificar(x,f.getVersion(),"Compra");if(x.getEstado()!=EstadoCompra.CONFIRMADA||x.getMovimientoEgreso()==null)throw new ReglaNegocioException("Sólo una compra confirmada puede cancelarse");String motivo=limpiar(f.getMotivo());if(motivo==null)throw new ReglaNegocioException("Explica el motivo de la cancelación");ZoneId z=ZoneId.of(x.getInstitucion().getZonaHoraria());LocalDateTime ahora=LocalDateTime.now(z).withSecond(0).withNano(0);var r=reversor.revertirMovimiento(x.getMovimientoEgreso().getId(),new ReversionFinancieraRequest(ahora,motivo,"CANCELACION_COMPRA:"+x.getId(),x.getMovimientoEgreso().getVersion()));x.setReversionFinanciera(reversiones.findById(r.id()).orElseThrow());x.setEstado(EstadoCompra.CANCELADA);x.setCanceladaEn(r.fecha());x.setCanceladaPor(actor(principal,x.getInstitucion().getId()));x.setMotivoCancelacion(motivo);compras.saveAndFlush(x);}
    @Transactional(readOnly=true) public CompraForm formulario(Long id){Compra x=obtener(id);validarAcceso(x);CompraForm f=new CompraForm();f.setInstitucionId(x.getInstitucion().getId());f.setPlantelId(x.getPlantel()==null?null:x.getPlantel().getId());f.setProveedorId(x.getProveedor().getId());f.setCuentaId(x.getCuenta().getId());f.setMotivoFinancieroId(x.getMotivoFinanciero().getId());f.setFechaOperacion(LocalDateTime.ofInstant(x.getFechaOperacion(),ZoneId.of(x.getInstitucion().getZonaHoraria())));f.setDocumentoReferencia(x.getDocumentoReferencia());f.setObservaciones(x.getObservaciones());f.setVersion(x.getVersion());f.setPartidas(x.getPartidas().stream().map(d->{CompraPartidaForm p=new CompraPartidaForm();p.setDescripcion(d.getDescripcion());p.setCantidad(d.getCantidad());p.setPrecioUnitario(d.getPrecioUnitario());p.setPorcentajeImpuesto(d.getPorcentajeImpuesto());return p;}).toList());return f;}
    @Transactional(readOnly=true) public CompraDetalleVista detalle(Long id){Compra x=obtener(id);validarAcceso(x);return vista(x);}
    @Transactional(readOnly=true) public List<CuentaCompraOpcion> cuentasActivas(Long institucionId){if(institucionId==null)return List.of();alcance.validarInstitucion(institucionId);Specification<CuentaFinanciera>s=alcance.<CuentaFinanciera>especificacion(escuela.admin.dto.ModuloCatalogo.CUENTAS_FINANCIERAS).and((r,q,cb)->cb.and(cb.equal(r.get("institucion").get("id"),institucionId),cb.isTrue(r.get("activo"))));return cuentas.findAll(s,Sort.by("nombre")).stream().map(c->new CuentaCompraOpcion(c.getId(),c.getInstitucion().getId(),c.getPlantel()==null?null:c.getPlantel().getId(),c.getNombre(),c.getCodigo(),c.getTipo().name(),c.getMoneda())).toList();}
    @Transactional(readOnly=true) public Page<CompraFila> listar(FiltroCompra entrada){FiltroCompra f=entrada.normalizado();if(f.institucionId()==null)throw new ReglaNegocioException("Selecciona una institución");alcance.validarInstitucion(f.institucionId());if(f.desde()!=null&&f.hasta()!=null&&f.hasta().isBefore(f.desde()))throw new ReglaNegocioException("La fecha final debe ser igual o posterior a la inicial");Specification<Compra>s=alcanceCompra(f.institucionId());if(f.plantelId()!=null)s=s.and((r,q,cb)->cb.equal(r.get("plantel").get("id"),f.plantelId()));if(f.proveedorId()!=null)s=s.and((r,q,cb)->cb.equal(r.get("proveedor").get("id"),f.proveedorId()));if(f.cuentaId()!=null)s=s.and((r,q,cb)->cb.equal(r.get("cuenta").get("id"),f.cuentaId()));if(f.estado()!=null)s=s.and((r,q,cb)->cb.equal(r.get("estado"),f.estado()));ZoneId z=zona(f.institucionId());if(f.desde()!=null){Instant d=f.desde().atStartOfDay(z).toInstant();s=s.and((r,q,cb)->cb.greaterThanOrEqualTo(r.get("fechaOperacion"),d));}if(f.hasta()!=null){Instant h=f.hasta().plusDays(1).atStartOfDay(z).toInstant();s=s.and((r,q,cb)->cb.lessThan(r.get("fechaOperacion"),h));}if(!f.texto().isBlank()){String p="%"+f.texto().toLowerCase(Locale.ROOT)+"%";s=s.and((r,q,cb)->cb.or(cb.like(cb.lower(r.get("folio")),p),cb.like(cb.lower(cb.coalesce(r.get("documentoReferencia"),"")),p),cb.like(cb.lower(r.get("proveedor").get("razonSocial")),p),cb.like(cb.lower(cb.coalesce(r.get("proveedor").get("rfc"),"")),p)));}return compras.findAll(s,PageRequest.of(f.pagina(),f.tamanio(),Sort.by(Sort.Order.desc("fechaOperacion"),Sort.Order.desc("id")))).map(this::fila);}
    private Contexto validar(CompraForm f,Long id){Institucion i=instituciones.findById(f.getInstitucionId()).orElseThrow(()->new RecursoNoEncontradoException("la institución",f.getInstitucionId()));alcance.validarInstitucion(i.getId());Proveedor p=proveedores.findById(f.getProveedorId()).orElseThrow(()->new RecursoNoEncontradoException("el proveedor",f.getProveedorId()));CuentaFinanciera c=cuentas.findById(f.getCuentaId()).orElseThrow(()->new RecursoNoEncontradoException("la cuenta",f.getCuentaId()));MotivoFinanciero m=motivos.findById(f.getMotivoFinancieroId()).orElseThrow(()->new RecursoNoEncontradoException("el motivo financiero",f.getMotivoFinancieroId()));if(!p.isActivo()||!p.getInstitucion().getId().equals(i.getId()))throw new ReglaNegocioException("El proveedor no está activo o no pertenece a la institución");if(!c.isActivo()||!c.getInstitucion().getId().equals(i.getId()))throw new ReglaNegocioException("La cuenta no está activa o no pertenece a la institución");if(!m.isActivo()||!m.getInstitucion().getId().equals(i.getId())||m.getNaturaleza()==NaturalezaMotivoFinanciero.INGRESO)throw new ReglaNegocioException("La categoría financiera debe admitir egresos");Plantel pl=null;if(f.getPlantelId()!=null){pl=planteles.findById(f.getPlantelId()).orElseThrow(()->new RecursoNoEncontradoException("el plantel",f.getPlantelId()));if(!pl.getInstitucion().getId().equals(i.getId()))throw new ReglaNegocioException("El plantel no pertenece a la institución");alcance.validarPlantel(pl.getId());}else alcance.validarAdministracionInstitucional(i.getId());if(c.getPlantel()!=null&&(pl==null||!c.getPlantel().getId().equals(pl.getId())))throw new ReglaNegocioException("El plantel debe coincidir con el alcance de la cuenta");if(f.getFechaOperacion()==null)throw new ReglaNegocioException("Indica la fecha de compra");if(f.getPartidas()==null||f.getPartidas().isEmpty())throw new ReglaNegocioException("Agrega al menos una partida");return new Contexto(i,pl,p,c,m);}
    private void copiar(Compra x,CompraForm f,Contexto c){x.setPlantel(c.plantel());x.setProveedor(c.proveedor());x.setCuenta(c.cuenta());x.setMotivoFinanciero(c.motivo());x.setFechaOperacion(f.getFechaOperacion().atZone(ZoneId.of(c.institucion().getZonaHoraria())).toInstant());x.setDocumentoReferencia(limpiar(f.getDocumentoReferencia()));x.setObservaciones(limpiar(f.getObservaciones()));x.getPartidas().clear();BigDecimal sub=BigDecimal.ZERO,imp=BigDecimal.ZERO;int orden=1;for(CompraPartidaForm p:f.getPartidas()){CompraDetalle d=new CompraDetalle();d.setCompra(x);d.setDescripcion(limpiar(p.getDescripcion()));d.setCantidad(p.getCantidad().setScale(3,RoundingMode.HALF_UP));d.setPrecioUnitario(p.getPrecioUnitario().setScale(2,RoundingMode.HALF_UP));d.setPorcentajeImpuesto(p.getPorcentajeImpuesto().setScale(2,RoundingMode.HALF_UP));d.setSubtotal(d.getCantidad().multiply(d.getPrecioUnitario()).setScale(2,RoundingMode.HALF_UP));d.setImpuesto(d.getSubtotal().multiply(d.getPorcentajeImpuesto()).divide(new BigDecimal("100"),2,RoundingMode.HALF_UP));d.setTotal(d.getSubtotal().add(d.getImpuesto()));d.setOrden(orden++);sub=sub.add(d.getSubtotal());imp=imp.add(d.getImpuesto());x.getPartidas().add(d);}x.setSubtotal(sub.setScale(2));x.setImpuesto(imp.setScale(2));x.setTotal(sub.add(imp).setScale(2));if(x.getTotal().signum()<=0)throw new ReglaNegocioException("El total de la compra debe ser mayor a cero");}
    private Specification<Compra> alcanceCompra(Long institucionId){Set<Long> ids=alcance.plantelesActuales(institucionId);boolean institucional=alcance.alcanceInstitucionalActual(institucionId);return (r,q,cb)->institucional?cb.equal(r.get("institucion").get("id"),institucionId):cb.and(cb.equal(r.get("institucion").get("id"),institucionId),r.get("plantel").get("id").in(ids));}
    private void validarAcceso(Compra x){if(x.getPlantel()==null)alcance.validarAdministracionInstitucional(x.getInstitucion().getId());else alcance.validarPlantel(x.getPlantel().getId());}
    @Transactional(readOnly=true) public ZoneId zonaInstitucion(Long id){alcance.validarInstitucion(id);return zona(id);}
    private ZoneId zona(Long id){return ZoneId.of(instituciones.findById(id).orElseThrow(()->new RecursoNoEncontradoException("la institución",id)).getZonaHoraria());}
    private escuela.seguridad.entity.Usuario actor(UsuarioPrincipal p,Long i){if(p==null||p.usuarioId()==null)throw new AccessDeniedException("La operación requiere un usuario identificado");var u=usuarios.findById(p.usuarioId()).orElseThrow(()->new AccessDeniedException("El usuario ya no está disponible"));if(!u.getInstitucion().getId().equals(i))throw new AccessDeniedException("El usuario no pertenece a la institución");return u;}
    private Compra bloquear(Long id){return compras.findByIdForUpdate(id).orElseThrow(()->new RecursoNoEncontradoException("la compra",id));}private Compra obtener(Long id){return compras.findById(id).orElseThrow(()->new RecursoNoEncontradoException("la compra",id));}
    private CompraFila fila(Compra x){return new CompraFila(x.getId(),x.getFolio(),x.getFechaOperacion(),x.getProveedor().getRazonSocial(),x.getProveedor().getRfc(),x.getPlantel()==null?"Institucional":x.getPlantel().getNombre(),x.getCuenta().getNombre(),x.getDocumentoReferencia(),x.getTotal(),x.getEstado(),x.getMovimientoEgreso()==null?null:x.getMovimientoEgreso().getId(),x.getVersion());}
    private CompraDetalleVista vista(Compra x){return new CompraDetalleVista(x.getId(),x.getFolio(),x.getInstitucion().getId(),x.getInstitucion().getNombre(),x.getPlantel()==null?null:x.getPlantel().getId(),x.getPlantel()==null?"Institucional":x.getPlantel().getNombre(),x.getProveedor().getRazonSocial(),x.getProveedor().getRfc(),x.getCuenta().getNombre(),x.getMotivoFinanciero().getNombre(),x.getFechaOperacion(),x.getDocumentoReferencia(),x.getObservaciones(),x.getSubtotal(),x.getImpuesto(),x.getTotal(),x.getEstado(),x.getMovimientoEgreso()==null?null:x.getMovimientoEgreso().getId(),x.getReversionFinanciera()==null?null:x.getReversionFinanciera().getId(),x.getCanceladaEn(),x.getCanceladaPor()==null?null:x.getCanceladaPor().getUsername(),x.getMotivoCancelacion(),x.getVersion(),x.getPartidas().stream().map(d->new CompraDetalleVista.Partida(d.getDescripcion(),d.getCantidad(),d.getPrecioUnitario(),d.getPorcentajeImpuesto(),d.getSubtotal(),d.getImpuesto(),d.getTotal())).toList());}
    private record Contexto(Institucion institucion,Plantel plantel,Proveedor proveedor,CuentaFinanciera cuenta,MotivoFinanciero motivo){}
}
