CREATE TABLE inscripcion (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id                   BIGINT NOT NULL REFERENCES alumno(id),
    plantel_id                  BIGINT NOT NULL REFERENCES plantel(id),
    ciclo_escolar_id            BIGINT NOT NULL REFERENCES ciclo_escolar(id),
    grado_id                    BIGINT NOT NULL REFERENCES grado(id),
    numero_inscripcion          VARCHAR(60) NOT NULL,
    fecha_inscripcion           DATE NOT NULL,
    fecha_inicio               DATE NOT NULL,
    fecha_fin                  DATE,
    estado                     VARCHAR(20) NOT NULL,
    motivo_baja_cancelacion    VARCHAR(2000),
    inscripcion_anterior_id    BIGINT REFERENCES inscripcion(id),
    observaciones              VARCHAR(4000),
    creado_en                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id              BIGINT,
    actualizado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id         BIGINT,
    version                    BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_inscripcion_estado CHECK (
        estado IN ('PREINSCRITA', 'ACTIVA', 'BAJA', 'FINALIZADA', 'CANCELADA')
    ),
    CONSTRAINT ck_inscripcion_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_inscripcion_motivo CHECK (
        (estado IN ('BAJA', 'CANCELADA') AND motivo_baja_cancelacion IS NOT NULL
            AND btrim(motivo_baja_cancelacion) <> '')
        OR estado NOT IN ('BAJA', 'CANCELADA')
    ),
    CONSTRAINT ck_inscripcion_version CHECK (version >= 0),
    CONSTRAINT ux_inscripcion_anterior UNIQUE (inscripcion_anterior_id)
);

CREATE INDEX ix_inscripcion_alumno_estado ON inscripcion (alumno_id, estado, fecha_inicio, fecha_fin);
CREATE INDEX ix_inscripcion_plantel_ciclo ON inscripcion (plantel_id, ciclo_escolar_id, grado_id);
CREATE INDEX ix_inscripcion_numero_normalizado ON inscripcion (upper(btrim(numero_inscripcion)));
CREATE UNIQUE INDEX ux_inscripcion_alumno_abierta
    ON inscripcion (alumno_id)
    WHERE estado IN ('PREINSCRITA', 'ACTIVA') AND fecha_fin IS NULL;

CREATE TABLE asignacion_grupo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id      BIGINT NOT NULL REFERENCES inscripcion(id),
    grupo_id            BIGINT NOT NULL REFERENCES grupo(id),
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE,
    motivo              VARCHAR(2000),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_asignacion_grupo_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_asignacion_grupo_version CHECK (version >= 0)
);

CREATE INDEX ix_asignacion_grupo_grupo_vigencia
    ON asignacion_grupo (grupo_id, fecha_inicio, fecha_fin);
CREATE INDEX ix_asignacion_grupo_inscripcion_historial
    ON asignacion_grupo (inscripcion_id, fecha_inicio DESC);
CREATE UNIQUE INDEX ux_asignacion_grupo_abierta
    ON asignacion_grupo (inscripcion_id)
    WHERE fecha_fin IS NULL;

INSERT INTO permiso (codigo, descripcion) VALUES
    ('INSCRIPCION_LEER', 'Consultar inscripciones y trayectoria académica'),
    ('INSCRIPCION_ADMINISTRAR', 'Crear y modificar inscripciones y asignaciones de grupo');
