CREATE TABLE concepto_cobro (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    codigo              VARCHAR(50) NOT NULL,
    nombre              VARCHAR(150) NOT NULL,
    descripcion         VARCHAR(2000),
    categoria           VARCHAR(20) NOT NULL,
    permite_beca        BOOLEAN NOT NULL DEFAULT FALSE,
    permite_descuento   BOOLEAN NOT NULL DEFAULT FALSE,
    permite_recargo     BOOLEAN NOT NULL DEFAULT FALSE,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    busqueda_autocomplete TEXT GENERATED ALWAYS AS (
        lower(btrim(codigo) || ' ' || btrim(nombre))
    ) STORED,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_concepto_cobro_categoria CHECK (
        categoria IN ('COLEGIATURA', 'INSCRIPCION', 'SERVICIO', 'MATERIAL', 'OTRO')
    ),
    CONSTRAINT ck_concepto_cobro_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_concepto_cobro_codigo
    ON concepto_cobro (institucion_id, upper(btrim(codigo)));
CREATE INDEX ix_concepto_cobro_institucion_estado
    ON concepto_cobro (institucion_id, activo, categoria);
CREATE INDEX ix_concepto_cobro_busqueda_gin
    ON concepto_cobro USING gin (busqueda_autocomplete gin_trgm_ops);
CREATE INDEX ix_inscripcion_numero_busqueda_gin
    ON inscripcion USING gin (lower(numero_inscripcion) gin_trgm_ops);

CREATE TABLE cuota_alumno (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id                  BIGINT NOT NULL REFERENCES inscripcion(id),
    concepto_cobro_id               BIGINT NOT NULL REFERENCES concepto_cobro(id),
    importe_base                    NUMERIC(14,2) NOT NULL,
    moneda                          VARCHAR(3) NOT NULL,
    frecuencia                      VARCHAR(12) NOT NULL,
    fecha_inicio                    DATE NOT NULL,
    fecha_fin                       DATE NOT NULL,
    dia_vencimiento                 INTEGER,
    fecha_vencimiento_unico         DATE,
    generacion_automatica           BOOLEAN NOT NULL DEFAULT FALSE,
    motivo_importe_personalizado    VARCHAR(2000),
    estado                          VARCHAR(15) NOT NULL,
    creado_en                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id                   BIGINT,
    actualizado_en                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id              BIGINT,
    version                         BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_cuota_alumno_importe CHECK (importe_base >= 0),
    CONSTRAINT ck_cuota_alumno_moneda CHECK (moneda = upper(moneda) AND char_length(moneda) = 3),
    CONSTRAINT ck_cuota_alumno_frecuencia CHECK (frecuencia IN ('UNICA', 'MENSUAL')),
    CONSTRAINT ck_cuota_alumno_estado CHECK (estado IN ('ACTIVA', 'SUSPENDIDA', 'FINALIZADA')),
    CONSTRAINT ck_cuota_alumno_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_cuota_alumno_vencimiento CHECK (
        (frecuencia = 'MENSUAL' AND dia_vencimiento BETWEEN 1 AND 31
            AND fecha_vencimiento_unico IS NULL)
        OR
        (frecuencia = 'UNICA' AND dia_vencimiento IS NULL
            AND fecha_vencimiento_unico IS NOT NULL)
    ),
    CONSTRAINT ck_cuota_alumno_version CHECK (version >= 0)
);

CREATE INDEX ix_cuota_alumno_inscripcion_estado
    ON cuota_alumno (inscripcion_id, estado, fecha_inicio, fecha_fin);
CREATE INDEX ix_cuota_alumno_concepto_vigencia
    ON cuota_alumno (concepto_cobro_id, fecha_inicio, fecha_fin);
CREATE INDEX ix_cuota_alumno_generacion
    ON cuota_alumno (generacion_automatica, estado, fecha_inicio, fecha_fin)
    WHERE generacion_automatica = TRUE AND estado = 'ACTIVA';

INSERT INTO permiso (codigo, descripcion) VALUES
    ('CONCEPTO_COBRO_LEER', 'Consultar conceptos de cobro'),
    ('CONCEPTO_COBRO_ADMINISTRAR', 'Crear y modificar conceptos de cobro'),
    ('CUOTA_ALUMNO_LEER', 'Consultar cuotas individuales por alumno'),
    ('CUOTA_ALUMNO_ADMINISTRAR', 'Configurar cuotas individuales y su generación automática');
