CREATE TABLE cargo (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id           BIGINT NOT NULL REFERENCES inscripcion(id),
    concepto_cobro_id        BIGINT NOT NULL REFERENCES concepto_cobro(id),
    cuota_alumno_id          BIGINT REFERENCES cuota_alumno(id),
    clave_generacion         VARCHAR(180) NOT NULL,
    descripcion              VARCHAR(250) NOT NULL,
    periodo_cobro_inicio     DATE NOT NULL,
    periodo_cobro_fin        DATE NOT NULL,
    periodo_academico_id     BIGINT REFERENCES periodo_academico(id),
    fecha_emision            DATE NOT NULL,
    fecha_vencimiento        DATE NOT NULL,
    importe_original         NUMERIC(14,2) NOT NULL,
    moneda                   VARCHAR(3) NOT NULL,
    estado_registro          VARCHAR(12) NOT NULL DEFAULT 'EMITIDO',
    cancelado_en             TIMESTAMPTZ,
    motivo_cancelacion       VARCHAR(2000),
    creado_en                TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id            BIGINT,
    actualizado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id       BIGINT,
    version                  BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_cargo_clave_generacion UNIQUE (clave_generacion),
    CONSTRAINT ck_cargo_descripcion CHECK (btrim(descripcion) <> ''),
    CONSTRAINT ck_cargo_periodo CHECK (periodo_cobro_fin >= periodo_cobro_inicio),
    CONSTRAINT ck_cargo_importe CHECK (importe_original >= 0),
    CONSTRAINT ck_cargo_moneda CHECK (moneda = upper(moneda) AND char_length(moneda) = 3),
    CONSTRAINT ck_cargo_estado CHECK (estado_registro IN ('EMITIDO', 'CANCELADO')),
    CONSTRAINT ck_cargo_cancelacion CHECK (
        (estado_registro = 'EMITIDO' AND cancelado_en IS NULL AND motivo_cancelacion IS NULL)
        OR
        (estado_registro = 'CANCELADO' AND cancelado_en IS NOT NULL
            AND motivo_cancelacion IS NOT NULL AND btrim(motivo_cancelacion) <> '')
    ),
    CONSTRAINT ck_cargo_version CHECK (version >= 0)
);

CREATE INDEX ix_cargo_inscripcion_estado_vencimiento
    ON cargo (inscripcion_id, estado_registro, fecha_vencimiento);
CREATE INDEX ix_cargo_concepto_emision
    ON cargo (concepto_cobro_id, fecha_emision DESC);
CREATE INDEX ix_cargo_cuota_periodo
    ON cargo (cuota_alumno_id, periodo_cobro_inicio)
    WHERE cuota_alumno_id IS NOT NULL;
CREATE INDEX ix_cargo_periodo_academico
    ON cargo (periodo_academico_id)
    WHERE periodo_academico_id IS NOT NULL;

CREATE INDEX ix_periodo_academico_busqueda_cargo
    ON periodo_academico USING gin ((lower(codigo || ' ' || nombre)) gin_trgm_ops);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('CARGO_LEER', 'Consultar cargos individuales por alumno'),
    ('CARGO_ADMINISTRAR', 'Emitir, generar y cancelar cargos individuales');
