CREATE TABLE tipo_beca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(2000),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_tipo_beca_institucion_codigo UNIQUE (institucion_id, codigo),
    CONSTRAINT ck_tipo_beca_codigo CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_tipo_beca_nombre CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_tipo_beca_version CHECK (version >= 0)
);

CREATE TABLE beca_alumno (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id BIGINT NOT NULL REFERENCES inscripcion(id),
    tipo_beca_id BIGINT NOT NULL REFERENCES tipo_beca(id),
    concepto_cobro_id BIGINT NOT NULL REFERENCES concepto_cobro(id),
    modalidad VARCHAR(12) NOT NULL,
    porcentaje NUMERIC(7,4),
    monto_fijo NUMERIC(14,2),
    moneda VARCHAR(3),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    motivo VARCHAR(2000) NOT NULL,
    autorizado_por_id BIGINT REFERENCES usuario(id),
    estado VARCHAR(12) NOT NULL DEFAULT 'ACTIVA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_beca_modalidad CHECK (modalidad IN ('PORCENTAJE', 'MONTO_FIJO')),
    CONSTRAINT ck_beca_valor CHECK (
        (modalidad = 'PORCENTAJE' AND porcentaje > 0 AND porcentaje <= 100
            AND monto_fijo IS NULL AND moneda IS NULL)
        OR
        (modalidad = 'MONTO_FIJO' AND monto_fijo > 0
            AND porcentaje IS NULL AND moneda IS NOT NULL
            AND moneda = upper(moneda) AND char_length(moneda) = 3)
    ),
    CONSTRAINT ck_beca_vigencia CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_beca_motivo CHECK (btrim(motivo) <> ''),
    CONSTRAINT ck_beca_estado CHECK (estado IN ('ACTIVA', 'SUSPENDIDA', 'FINALIZADA', 'CANCELADA')),
    CONSTRAINT ck_beca_version CHECK (version >= 0)
);

CREATE INDEX ix_beca_alumno_inscripcion_concepto_estado
    ON beca_alumno (inscripcion_id, concepto_cobro_id, estado, fecha_inicio, fecha_fin);
CREATE INDEX ix_beca_alumno_tipo ON beca_alumno (tipo_beca_id);

CREATE TABLE ajuste_cargo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cargo_id BIGINT NOT NULL REFERENCES cargo(id),
    tipo VARCHAR(12) NOT NULL,
    efecto VARCHAR(11) NOT NULL,
    monto NUMERIC(14,2) NOT NULL,
    base_calculo NUMERIC(14,2),
    porcentaje_aplicado NUMERIC(7,4),
    beca_alumno_id BIGINT REFERENCES beca_alumno(id),
    motivo VARCHAR(2000) NOT NULL,
    autorizado_por_id BIGINT REFERENCES usuario(id),
    fecha_efectiva DATE NOT NULL,
    reversa_de_id BIGINT UNIQUE REFERENCES ajuste_cargo(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_ajuste_tipo CHECK (tipo IN ('BECA', 'DESCUENTO', 'RECARGO', 'CORRECCION')),
    CONSTRAINT ck_ajuste_efecto CHECK (efecto IN ('AUMENTO', 'DISMINUCION')),
    CONSTRAINT ck_ajuste_monto CHECK (monto > 0),
    CONSTRAINT ck_ajuste_base CHECK (base_calculo IS NULL OR base_calculo >= 0),
    CONSTRAINT ck_ajuste_porcentaje CHECK (porcentaje_aplicado IS NULL
        OR (porcentaje_aplicado > 0 AND porcentaje_aplicado <= 100)),
    CONSTRAINT ck_ajuste_reglas CHECK (
        (tipo = 'BECA' AND efecto = 'DISMINUCION' AND beca_alumno_id IS NOT NULL)
        OR (tipo = 'DESCUENTO' AND efecto = 'DISMINUCION' AND beca_alumno_id IS NULL)
        OR (tipo = 'RECARGO' AND efecto = 'AUMENTO' AND beca_alumno_id IS NULL)
        OR (tipo = 'CORRECCION' AND beca_alumno_id IS NULL)
    ),
    CONSTRAINT ck_ajuste_motivo CHECK (btrim(motivo) <> ''),
    CONSTRAINT ck_ajuste_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_ajuste_cargo_beca
    ON ajuste_cargo (cargo_id, beca_alumno_id)
    WHERE tipo = 'BECA' AND reversa_de_id IS NULL;
CREATE INDEX ix_ajuste_cargo_cargo ON ajuste_cargo (cargo_id, id);
CREATE INDEX ix_ajuste_cargo_fecha ON ajuste_cargo (fecha_efectiva DESC);

ALTER TABLE tipo_beca ADD COLUMN busqueda_autocomplete TEXT GENERATED ALWAYS AS
    (lower(codigo || ' ' || nombre || ' ' || coalesce(descripcion, ''))) STORED;
CREATE INDEX ix_tipo_beca_busqueda_autocomplete
    ON tipo_beca USING gin (busqueda_autocomplete gin_trgm_ops);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('TIPO_BECA_LEER', 'Consultar el catálogo de tipos de beca'),
    ('TIPO_BECA_ADMINISTRAR', 'Administrar el catálogo de tipos de beca'),
    ('BECA_ALUMNO_LEER', 'Consultar becas individuales por alumno'),
    ('BECA_ALUMNO_ADMINISTRAR', 'Asignar y administrar becas individuales'),
    ('AJUSTE_CARGO_LEER', 'Consultar ajustes históricos de cargos'),
    ('AJUSTE_CARGO_ADMINISTRAR', 'Registrar y reversar ajustes de cargos');
