CREATE TABLE politica_recargo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    concepto_cobro_id BIGINT NOT NULL UNIQUE REFERENCES concepto_cobro(id),
    modalidad VARCHAR(12) NOT NULL,
    porcentaje NUMERIC(7,4),
    monto_fijo NUMERIC(14,2),
    moneda VARCHAR(3),
    dias_gracia INTEGER NOT NULL DEFAULT 0,
    periodicidad VARCHAR(10) NOT NULL,
    tipo_limite VARCHAR(20) NOT NULL,
    valor_limite NUMERIC(14,4),
    generacion_automatica BOOLEAN NOT NULL DEFAULT TRUE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_politica_recargo_modalidad CHECK (modalidad IN ('PORCENTAJE', 'MONTO_FIJO')),
    CONSTRAINT ck_politica_recargo_valor CHECK (
        (modalidad = 'PORCENTAJE' AND porcentaje > 0 AND porcentaje <= 100
            AND monto_fijo IS NULL AND moneda IS NULL)
        OR
        (modalidad = 'MONTO_FIJO' AND monto_fijo > 0 AND porcentaje IS NULL
            AND moneda IS NOT NULL AND moneda = upper(moneda) AND char_length(moneda) = 3)
    ),
    CONSTRAINT ck_politica_recargo_gracia CHECK (dias_gracia BETWEEN 0 AND 365),
    CONSTRAINT ck_politica_recargo_periodicidad CHECK (periodicidad IN ('UNICA', 'MENSUAL')),
    CONSTRAINT ck_politica_recargo_limite CHECK (
        (tipo_limite = 'SIN_LIMITE' AND valor_limite IS NULL)
        OR (tipo_limite = 'PORCENTAJE_ORIGINAL' AND valor_limite > 0 AND valor_limite <= 1000)
        OR (tipo_limite = 'MONTO_FIJO' AND valor_limite > 0)
    ),
    CONSTRAINT ck_politica_recargo_version CHECK (version >= 0)
);

ALTER TABLE ajuste_cargo
    ADD COLUMN politica_recargo_id BIGINT REFERENCES politica_recargo(id),
    ADD COLUMN clave_generacion VARCHAR(180);

ALTER TABLE ajuste_cargo ADD CONSTRAINT ck_ajuste_recargo_automatico CHECK (
    (politica_recargo_id IS NULL AND clave_generacion IS NULL)
    OR (tipo = 'RECARGO' AND efecto = 'AUMENTO'
        AND politica_recargo_id IS NOT NULL AND clave_generacion IS NOT NULL)
);

CREATE UNIQUE INDEX ux_ajuste_cargo_clave_generacion
    ON ajuste_cargo (clave_generacion) WHERE clave_generacion IS NOT NULL;
CREATE INDEX ix_politica_recargo_activa
    ON politica_recargo (concepto_cobro_id, activo, generacion_automatica);
CREATE INDEX ix_ajuste_cargo_politica
    ON ajuste_cargo (politica_recargo_id, cargo_id)
    WHERE politica_recargo_id IS NOT NULL;

INSERT INTO permiso (codigo, descripcion) VALUES
    ('POLITICA_RECARGO_LEER', 'Consultar políticas de recargo automático'),
    ('POLITICA_RECARGO_ADMINISTRAR', 'Configurar y ejecutar recargos automáticos');
