CREATE TABLE cuenta_financiera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    plantel_id BIGINT REFERENCES plantel(id),
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    tipo VARCHAR(10) NOT NULL,
    banco_nombre VARCHAR(120),
    titular VARCHAR(150),
    numero_cuenta VARCHAR(34),
    clabe VARCHAR(18),
    moneda VARCHAR(3) NOT NULL,
    saldo_inicial NUMERIC(19,2) NOT NULL DEFAULT 0,
    fecha_saldo_inicial DATE NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_cuenta_financiera_tipo CHECK (tipo IN ('CAJA', 'BANCO', 'INVERSION')),
    CONSTRAINT ck_cuenta_financiera_moneda CHECK (
        moneda = upper(moneda) AND char_length(moneda) = 3
    ),
    CONSTRAINT ck_cuenta_financiera_saldo_inicial CHECK (saldo_inicial >= 0),
    CONSTRAINT ck_cuenta_financiera_clabe CHECK (
        clabe IS NULL OR clabe ~ '^[0-9]{18}$'
    ),
    CONSTRAINT ck_cuenta_financiera_datos CHECK (
        (tipo = 'CAJA' AND banco_nombre IS NULL AND numero_cuenta IS NULL AND clabe IS NULL)
        OR
        (tipo IN ('BANCO', 'INVERSION') AND banco_nombre IS NOT NULL
            AND (numero_cuenta IS NOT NULL OR clabe IS NOT NULL))
    ),
    CONSTRAINT ck_cuenta_financiera_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_cuenta_financiera_codigo
    ON cuenta_financiera (institucion_id, lower(codigo));
CREATE INDEX ix_cuenta_financiera_institucion_plantel
    ON cuenta_financiera (institucion_id, plantel_id, activo);
CREATE INDEX ix_cuenta_financiera_busqueda
    ON cuenta_financiera (institucion_id, lower(nombre));

INSERT INTO permiso (codigo, descripcion) VALUES
    ('CUENTA_FINANCIERA_LEER', 'Consultar cuentas financieras y sus saldos'),
    ('CUENTA_FINANCIERA_ADMINISTRAR', 'Administrar cuentas financieras');
