CREATE TABLE pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    plantel_registro_id BIGINT NOT NULL REFERENCES plantel(id),
    tutor_id BIGINT NOT NULL REFERENCES tutor(id),
    nombre_pagador VARCHAR(180),
    folio VARCHAR(50) NOT NULL,
    clave_idempotencia VARCHAR(100) NOT NULL,
    fecha_pago TIMESTAMPTZ NOT NULL,
    monto NUMERIC(19,2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    metodo VARCHAR(20) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_VALIDACION',
    cuenta_declarada_id BIGINT REFERENCES cuenta_financiera(id),
    cuenta_destino_id BIGINT REFERENCES cuenta_financiera(id),
    referencia VARCHAR(150),
    validado_por_id BIGINT REFERENCES usuario(id),
    validado_en TIMESTAMPTZ,
    motivo_rechazo_cancelacion VARCHAR(2000),
    observaciones VARCHAR(4000),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_pago_monto CHECK (monto > 0),
    CONSTRAINT ck_pago_moneda CHECK (moneda = upper(moneda) AND char_length(moneda) = 3),
    CONSTRAINT ck_pago_metodo CHECK (metodo IN ('EFECTIVO', 'TRANSFERENCIA')),
    CONSTRAINT ck_pago_estado CHECK (estado IN ('PENDIENTE_VALIDACION', 'VALIDADO', 'RECHAZADO', 'CANCELADO')),
    CONSTRAINT ck_pago_validacion CHECK (
        (estado = 'VALIDADO' AND cuenta_destino_id IS NOT NULL AND validado_por_id IS NOT NULL
            AND validado_en IS NOT NULL AND motivo_rechazo_cancelacion IS NULL)
        OR (estado = 'PENDIENTE_VALIDACION' AND cuenta_destino_id IS NULL AND validado_por_id IS NULL
            AND validado_en IS NULL AND motivo_rechazo_cancelacion IS NULL)
        OR (estado IN ('RECHAZADO', 'CANCELADO') AND motivo_rechazo_cancelacion IS NOT NULL)
    ),
    CONSTRAINT ck_pago_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_pago_folio ON pago (institucion_id, lower(folio));
CREATE UNIQUE INDEX ux_pago_idempotencia ON pago (institucion_id, clave_idempotencia);
CREATE INDEX ix_pago_institucion_estado_fecha ON pago (institucion_id, estado, fecha_pago DESC);
CREATE INDEX ix_pago_plantel_estado ON pago (plantel_registro_id, estado, id DESC);
CREATE INDEX ix_pago_tutor ON pago (tutor_id, id DESC);

CREATE TABLE comprobante_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL REFERENCES pago(id),
    archivo_id BIGINT NOT NULL REFERENCES archivo(id),
    observaciones VARCHAR(1000),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_comprobante_pago_archivo UNIQUE (archivo_id),
    CONSTRAINT ux_comprobante_pago_relacion UNIQUE (pago_id, archivo_id),
    CONSTRAINT ck_comprobante_pago_version CHECK (version >= 0)
);

CREATE INDEX ix_comprobante_pago_pago ON comprobante_pago (pago_id, id);

CREATE TABLE solicitud_aplicacion_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL REFERENCES pago(id),
    cargo_id BIGINT NOT NULL REFERENCES cargo(id),
    monto_solicitado NUMERIC(19,2) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_solicitud_aplicacion_pago UNIQUE (pago_id, cargo_id),
    CONSTRAINT ck_solicitud_aplicacion_monto CHECK (monto_solicitado > 0),
    CONSTRAINT ck_solicitud_aplicacion_version CHECK (version >= 0)
);

CREATE INDEX ix_solicitud_aplicacion_pago_pago ON solicitud_aplicacion_pago (pago_id, id);
CREATE INDEX ix_solicitud_aplicacion_pago_cargo ON solicitud_aplicacion_pago (cargo_id, id);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('PAGO_LEER', 'Consultar pagos, comprobantes y distribución solicitada'),
    ('PAGO_REGISTRAR', 'Registrar pagos pendientes, comprobantes y distribución solicitada');
