CREATE TABLE motivo_financiero (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    naturaleza VARCHAR(10) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_motivo_financiero_naturaleza CHECK (naturaleza IN ('INGRESO', 'EGRESO', 'AMBOS')),
    CONSTRAINT ck_motivo_financiero_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_motivo_financiero_codigo
    ON motivo_financiero (institucion_id, lower(codigo));

INSERT INTO motivo_financiero (institucion_id, codigo, nombre, naturaleza, categoria)
SELECT id, 'COBROS_ESCOLARES', 'Cobros escolares', 'INGRESO', 'COBRANZA'
FROM institucion;

CREATE TABLE aplicacion_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pago_id BIGINT NOT NULL REFERENCES pago(id),
    cargo_id BIGINT NOT NULL REFERENCES cargo(id),
    solicitud_id BIGINT REFERENCES solicitud_aplicacion_pago(id),
    monto NUMERIC(19,2) NOT NULL,
    operacion VARCHAR(10) NOT NULL,
    fecha_aplicacion TIMESTAMPTZ NOT NULL,
    reversa_de_id BIGINT REFERENCES aplicacion_pago(id),
    motivo VARCHAR(2000),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_aplicacion_pago_solicitud UNIQUE (solicitud_id),
    CONSTRAINT ux_aplicacion_pago_reversa UNIQUE (reversa_de_id),
    CONSTRAINT ck_aplicacion_pago_monto CHECK (monto > 0),
    CONSTRAINT ck_aplicacion_pago_operacion CHECK (operacion IN ('APLICAR', 'REVERTIR')),
    CONSTRAINT ck_aplicacion_pago_reversa CHECK (
        (operacion = 'APLICAR' AND reversa_de_id IS NULL AND motivo IS NULL)
        OR (operacion = 'REVERTIR' AND reversa_de_id IS NOT NULL AND motivo IS NOT NULL)
    ),
    CONSTRAINT ck_aplicacion_pago_version CHECK (version >= 0)
);

CREATE INDEX ix_aplicacion_pago_pago ON aplicacion_pago (pago_id, id);
CREATE INDEX ix_aplicacion_pago_cargo ON aplicacion_pago (cargo_id, id);

CREATE TABLE movimiento_financiero (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    cuenta_id BIGINT NOT NULL REFERENCES cuenta_financiera(id),
    plantel_operacion_id BIGINT REFERENCES plantel(id),
    fecha_operacion TIMESTAMPTZ NOT NULL,
    secuencia_cuenta BIGINT NOT NULL,
    direccion VARCHAR(10) NOT NULL,
    clase VARCHAR(15) NOT NULL,
    monto NUMERIC(19,2) NOT NULL,
    motivo_financiero_id BIGINT NOT NULL REFERENCES motivo_financiero(id),
    concepto VARCHAR(250) NOT NULL,
    referencia VARCHAR(150),
    tercero_nombre VARCHAR(180),
    comprobante_archivo_id BIGINT REFERENCES archivo(id),
    pago_id BIGINT REFERENCES pago(id),
    reversa_de_id BIGINT REFERENCES movimiento_financiero(id),
    clave_idempotencia VARCHAR(120) NOT NULL,
    saldo_anterior NUMERIC(19,2) NOT NULL,
    saldo_posterior NUMERIC(19,2) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_movimiento_cuenta_secuencia UNIQUE (cuenta_id, secuencia_cuenta),
    CONSTRAINT ux_movimiento_pago UNIQUE (pago_id),
    CONSTRAINT ux_movimiento_reversa UNIQUE (reversa_de_id),
    CONSTRAINT ux_movimiento_idempotencia UNIQUE (institucion_id, clave_idempotencia),
    CONSTRAINT ck_movimiento_secuencia CHECK (secuencia_cuenta > 0),
    CONSTRAINT ck_movimiento_direccion CHECK (direccion IN ('INGRESO', 'EGRESO')),
    CONSTRAINT ck_movimiento_clase CHECK (clase IN ('COBRO', 'OPERACION', 'TRASPASO', 'DEVOLUCION', 'AJUSTE', 'REVERSO')),
    CONSTRAINT ck_movimiento_monto CHECK (monto > 0),
    CONSTRAINT ck_movimiento_saldos CHECK (saldo_anterior >= 0 AND saldo_posterior >= 0),
    CONSTRAINT ck_movimiento_cobro CHECK (
        (clase = 'COBRO' AND direccion = 'INGRESO' AND pago_id IS NOT NULL AND reversa_de_id IS NULL)
        OR clase <> 'COBRO'
    ),
    CONSTRAINT ck_movimiento_version CHECK (version >= 0)
);

CREATE INDEX ix_movimiento_cuenta_fecha ON movimiento_financiero (cuenta_id, fecha_operacion, id);
CREATE INDEX ix_movimiento_institucion_fecha ON movimiento_financiero (institucion_id, fecha_operacion, id);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('PAGO_VALIDAR', 'Validar o rechazar pagos y publicar sus aplicaciones e ingreso');
