CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE institucion (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                  VARCHAR(50) NOT NULL,
    nombre                  VARCHAR(200) NOT NULL,
    nombre_comercial        VARCHAR(200),
    razon_social            VARCHAR(250),
    rfc                     VARCHAR(13),
    email                   VARCHAR(254),
    telefono                VARCHAR(30),
    sitio_web               VARCHAR(300),
    domicilio_fiscal        TEXT,
    ciudad                  VARCHAR(120),
    estado                  VARCHAR(120),
    codigo_postal           VARCHAR(12),
    pais                    VARCHAR(2),
    logo_archivo_id         BIGINT,
    zona_horaria            VARCHAR(60) NOT NULL DEFAULT 'America/Mexico_City',
    moneda_predeterminada   VARCHAR(3) NOT NULL DEFAULT 'MXN',
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id           BIGINT,
    actualizado_en          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id      BIGINT,
    version                 BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_institucion_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_institucion_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_institucion_moneda CHECK (moneda_predeterminada ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_institucion_pais CHECK (pais IS NULL OR pais ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_institucion_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_institucion_codigo_normalizado ON institucion (lower(btrim(codigo)));

CREATE TABLE plantel (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    codigo              VARCHAR(50) NOT NULL,
    nombre              VARCHAR(200) NOT NULL,
    telefono            VARCHAR(30),
    email               VARCHAR(254),
    calle               VARCHAR(200),
    numero_exterior     VARCHAR(30),
    numero_interior     VARCHAR(30),
    colonia             VARCHAR(150),
    ciudad              VARCHAR(120),
    estado              VARCHAR(120),
    codigo_postal       VARCHAR(12),
    pais                VARCHAR(2),
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_plantel_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_plantel_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_plantel_pais CHECK (pais IS NULL OR pais ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_plantel_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_plantel_institucion_codigo
    ON plantel (institucion_id, lower(btrim(codigo)));
CREATE INDEX ix_plantel_institucion ON plantel (institucion_id);

CREATE TABLE nivel_educativo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    codigo              VARCHAR(50) NOT NULL,
    nombre              VARCHAR(150) NOT NULL,
    descripcion         TEXT,
    orden               INTEGER NOT NULL,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_nivel_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_nivel_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_nivel_orden_positivo CHECK (orden > 0),
    CONSTRAINT ck_nivel_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_nivel_institucion_codigo
    ON nivel_educativo (institucion_id, lower(btrim(codigo)));
CREATE UNIQUE INDEX ux_nivel_institucion_orden
    ON nivel_educativo (institucion_id, orden);
CREATE INDEX ix_nivel_institucion ON nivel_educativo (institucion_id);

CREATE TABLE plantel_nivel (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plantel_id              BIGINT NOT NULL REFERENCES plantel(id),
    nivel_educativo_id      BIGINT NOT NULL REFERENCES nivel_educativo(id),
    clave_centro_trabajo    VARCHAR(30),
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id           BIGINT,
    actualizado_en          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id      BIGINT,
    version                 BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_plantel_nivel UNIQUE (plantel_id, nivel_educativo_id),
    CONSTRAINT ck_plantel_nivel_version CHECK (version >= 0)
);

CREATE INDEX ix_plantel_nivel_nivel ON plantel_nivel (nivel_educativo_id);

CREATE TABLE grado (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nivel_educativo_id      BIGINT NOT NULL REFERENCES nivel_educativo(id),
    codigo                  VARCHAR(50) NOT NULL,
    nombre                  VARCHAR(150) NOT NULL,
    orden                   INTEGER NOT NULL,
    activo                  BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id           BIGINT,
    actualizado_en          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id      BIGINT,
    version                 BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_grado_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_grado_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_grado_orden_positivo CHECK (orden > 0),
    CONSTRAINT ck_grado_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_grado_nivel_codigo
    ON grado (nivel_educativo_id, lower(btrim(codigo)));
CREATE UNIQUE INDEX ux_grado_nivel_orden ON grado (nivel_educativo_id, orden);
CREATE INDEX ix_grado_nivel ON grado (nivel_educativo_id);

CREATE TABLE ciclo_escolar (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    codigo              VARCHAR(50) NOT NULL,
    nombre              VARCHAR(150) NOT NULL,
    fecha_inicio        DATE NOT NULL,
    fecha_fin           DATE NOT NULL,
    estado              VARCHAR(20) NOT NULL,
    es_predeterminado   BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_ciclo_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_ciclo_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_ciclo_fechas CHECK (fecha_inicio <= fecha_fin),
    CONSTRAINT ck_ciclo_estado CHECK (estado IN ('PLANIFICADO', 'ABIERTO', 'CERRADO')),
    CONSTRAINT ck_ciclo_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_ciclo_institucion_codigo
    ON ciclo_escolar (institucion_id, lower(btrim(codigo)));
CREATE UNIQUE INDEX ux_ciclo_predeterminado_por_institucion
    ON ciclo_escolar (institucion_id) WHERE es_predeterminado;
CREATE INDEX ix_ciclo_institucion_fechas
    ON ciclo_escolar (institucion_id, fecha_inicio, fecha_fin);

CREATE TABLE periodo_academico (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ciclo_escolar_id        BIGINT NOT NULL REFERENCES ciclo_escolar(id),
    nivel_educativo_id      BIGINT NOT NULL REFERENCES nivel_educativo(id),
    codigo                  VARCHAR(50) NOT NULL,
    nombre                  VARCHAR(150) NOT NULL,
    tipo                    VARCHAR(20) NOT NULL,
    orden                   INTEGER NOT NULL,
    fecha_inicio            DATE NOT NULL,
    fecha_fin               DATE NOT NULL,
    estado                  VARCHAR(20) NOT NULL,
    observaciones           TEXT,
    creado_en               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id           BIGINT,
    actualizado_en          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id      BIGINT,
    version                 BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_periodo_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_periodo_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_periodo_tipo CHECK (tipo IN ('BIMESTRE', 'TRIMESTRE', 'CUATRIMESTRE', 'SEMESTRE', 'OTRO')),
    CONSTRAINT ck_periodo_orden_positivo CHECK (orden > 0),
    CONSTRAINT ck_periodo_fechas CHECK (fecha_inicio <= fecha_fin),
    CONSTRAINT ck_periodo_estado CHECK (estado IN ('PLANIFICADO', 'ABIERTO', 'CERRADO')),
    CONSTRAINT ck_periodo_version CHECK (version >= 0),
    CONSTRAINT uq_periodo_orden UNIQUE (ciclo_escolar_id, nivel_educativo_id, orden),
    CONSTRAINT ex_periodo_sin_solapamiento EXCLUDE USING gist (
        ciclo_escolar_id WITH =,
        nivel_educativo_id WITH =,
        daterange(fecha_inicio, fecha_fin, '[]') WITH &&
    )
);

CREATE UNIQUE INDEX ux_periodo_ciclo_nivel_codigo
    ON periodo_academico (ciclo_escolar_id, nivel_educativo_id, lower(btrim(codigo)));
CREATE INDEX ix_periodo_nivel ON periodo_academico (nivel_educativo_id);

CREATE TABLE grupo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plantel_id          BIGINT NOT NULL REFERENCES plantel(id),
    ciclo_escolar_id    BIGINT NOT NULL REFERENCES ciclo_escolar(id),
    grado_id            BIGINT NOT NULL REFERENCES grado(id),
    nombre              VARCHAR(100) NOT NULL,
    turno               VARCHAR(20) NOT NULL,
    codigo              VARCHAR(50),
    aula                VARCHAR(100),
    capacidad           INTEGER,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_grupo_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_grupo_turno CHECK (turno IN ('MATUTINO', 'VESPERTINO', 'MIXTO')),
    CONSTRAINT ck_grupo_capacidad_positiva CHECK (capacidad IS NULL OR capacidad > 0),
    CONSTRAINT ck_grupo_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_grupo_asignacion
    ON grupo (plantel_id, ciclo_escolar_id, grado_id, turno, lower(btrim(nombre)));
CREATE UNIQUE INDEX ux_grupo_codigo
    ON grupo (plantel_id, ciclo_escolar_id, lower(btrim(codigo))) WHERE codigo IS NOT NULL;
CREATE INDEX ix_grupo_ciclo ON grupo (ciclo_escolar_id);
CREATE INDEX ix_grupo_grado ON grupo (grado_id);

CREATE OR REPLACE FUNCTION validar_plantel_nivel_misma_institucion()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    institucion_plantel BIGINT;
    institucion_nivel BIGINT;
BEGIN
    SELECT institucion_id INTO institucion_plantel FROM plantel WHERE id = NEW.plantel_id;
    SELECT institucion_id INTO institucion_nivel FROM nivel_educativo WHERE id = NEW.nivel_educativo_id;
    IF institucion_plantel IS DISTINCT FROM institucion_nivel THEN
        RAISE EXCEPTION 'El plantel y el nivel educativo deben pertenecer a la misma institución';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_plantel_nivel_misma_institucion
BEFORE INSERT OR UPDATE OF plantel_id, nivel_educativo_id ON plantel_nivel
FOR EACH ROW EXECUTE FUNCTION validar_plantel_nivel_misma_institucion();

CREATE OR REPLACE FUNCTION validar_periodo_academico()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    ciclo ciclo_escolar%ROWTYPE;
    institucion_nivel BIGINT;
BEGIN
    SELECT * INTO ciclo FROM ciclo_escolar WHERE id = NEW.ciclo_escolar_id;
    SELECT institucion_id INTO institucion_nivel FROM nivel_educativo WHERE id = NEW.nivel_educativo_id;
    IF ciclo.institucion_id IS DISTINCT FROM institucion_nivel THEN
        RAISE EXCEPTION 'El ciclo y el nivel educativo deben pertenecer a la misma institución';
    END IF;
    IF NEW.fecha_inicio < ciclo.fecha_inicio OR NEW.fecha_fin > ciclo.fecha_fin THEN
        RAISE EXCEPTION 'Las fechas del periodo deben estar dentro del ciclo escolar';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_validar_periodo_academico
BEFORE INSERT OR UPDATE OF ciclo_escolar_id, nivel_educativo_id, fecha_inicio, fecha_fin ON periodo_academico
FOR EACH ROW EXECUTE FUNCTION validar_periodo_academico();

CREATE OR REPLACE FUNCTION validar_grupo()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
    institucion_plantel BIGINT;
    institucion_ciclo BIGINT;
    nivel_grado BIGINT;
    institucion_grado BIGINT;
BEGIN
    SELECT institucion_id INTO institucion_plantel FROM plantel WHERE id = NEW.plantel_id;
    SELECT institucion_id INTO institucion_ciclo FROM ciclo_escolar WHERE id = NEW.ciclo_escolar_id;
    SELECT ne.id, ne.institucion_id INTO nivel_grado, institucion_grado
      FROM grado g JOIN nivel_educativo ne ON ne.id = g.nivel_educativo_id
     WHERE g.id = NEW.grado_id;

    IF institucion_plantel IS DISTINCT FROM institucion_ciclo
       OR institucion_plantel IS DISTINCT FROM institucion_grado THEN
        RAISE EXCEPTION 'Plantel, ciclo y grado deben pertenecer a la misma institución';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM plantel_nivel pn
         WHERE pn.plantel_id = NEW.plantel_id
           AND pn.nivel_educativo_id = nivel_grado
           AND pn.activo
    ) THEN
        RAISE EXCEPTION 'El plantel no ofrece activamente el nivel educativo del grado';
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER tr_validar_grupo
BEFORE INSERT OR UPDATE OF plantel_id, ciclo_escolar_id, grado_id ON grupo
FOR EACH ROW EXECUTE FUNCTION validar_grupo();
