CREATE TABLE transferencia_cuenta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    cuenta_origen_id BIGINT NOT NULL REFERENCES cuenta_financiera(id),
    cuenta_destino_id BIGINT NOT NULL REFERENCES cuenta_financiera(id),
    fecha TIMESTAMPTZ NOT NULL,
    monto NUMERIC(19,2) NOT NULL,
    referencia VARCHAR(150),
    observaciones TEXT,
    autorizado_por_id BIGINT NOT NULL REFERENCES usuario(id),
    clave_idempotencia VARCHAR(120) NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'APLICADA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_transferencia_idempotencia UNIQUE (institucion_id, clave_idempotencia),
    CONSTRAINT ck_transferencia_cuentas_distintas CHECK (cuenta_origen_id <> cuenta_destino_id),
    CONSTRAINT ck_transferencia_monto CHECK (monto > 0),
    CONSTRAINT ck_transferencia_estado CHECK (estado IN ('APLICADA', 'REVERTIDA')),
    CONSTRAINT ck_transferencia_version CHECK (version >= 0)
);

CREATE INDEX ix_transferencia_institucion_fecha
    ON transferencia_cuenta (institucion_id, fecha DESC, id DESC);
CREATE INDEX ix_transferencia_origen_fecha
    ON transferencia_cuenta (cuenta_origen_id, fecha DESC, id DESC);
CREATE INDEX ix_transferencia_destino_fecha
    ON transferencia_cuenta (cuenta_destino_id, fecha DESC, id DESC);

ALTER TABLE movimiento_financiero
    ADD COLUMN transferencia_id BIGINT REFERENCES transferencia_cuenta(id);

CREATE UNIQUE INDEX ux_movimiento_transferencia_lado
    ON movimiento_financiero (transferencia_id, direccion)
    WHERE transferencia_id IS NOT NULL;

ALTER TABLE movimiento_financiero
    ADD CONSTRAINT chk_movimiento_traspaso
    CHECK (
        (clase = 'TRASPASO' AND transferencia_id IS NOT NULL
            AND pago_id IS NULL AND reversa_de_id IS NULL)
        OR (clase <> 'TRASPASO' AND transferencia_id IS NULL)
    );

INSERT INTO permiso (codigo, descripcion)
VALUES ('TRANSFERENCIA_CUENTA_REGISTRAR',
        'Permite transferir fondos de manera atómica entre cuentas financieras')
ON CONFLICT DO NOTHING;

INSERT INTO motivo_financiero (institucion_id, codigo, nombre, naturaleza, categoria)
SELECT i.id, 'TRASPASO_INTERNO', 'Traspaso interno', 'AMBOS', 'TRANSFERENCIAS'
FROM institucion i
ON CONFLICT DO NOTHING;

