CREATE TABLE devolucion_pago (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    pago_id BIGINT NOT NULL REFERENCES pago(id),
    cuenta_origen_id BIGINT NOT NULL REFERENCES cuenta_financiera(id),
    monto NUMERIC(19,2) NOT NULL,
    fecha TIMESTAMPTZ NOT NULL,
    motivo VARCHAR(2000) NOT NULL,
    beneficiario VARCHAR(180) NOT NULL,
    referencia VARCHAR(150),
    autorizado_por_id BIGINT NOT NULL REFERENCES usuario(id),
    clave_idempotencia VARCHAR(120) NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'EJECUTADA',
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_devolucion_idempotencia UNIQUE (institucion_id, clave_idempotencia),
    CONSTRAINT ck_devolucion_monto CHECK (monto > 0),
    CONSTRAINT ck_devolucion_estado CHECK (estado IN ('SOLICITADA', 'EJECUTADA', 'CANCELADA')),
    CONSTRAINT ck_devolucion_textos CHECK (btrim(motivo) <> '' AND btrim(beneficiario) <> ''),
    CONSTRAINT ck_devolucion_version CHECK (version >= 0)
);

CREATE INDEX ix_devolucion_pago_fecha ON devolucion_pago (pago_id, fecha DESC, id DESC);
CREATE INDEX ix_devolucion_cuenta_fecha ON devolucion_pago (cuenta_origen_id, fecha DESC, id DESC);

ALTER TABLE aplicacion_pago
    ADD COLUMN devolucion_pago_id BIGINT REFERENCES devolucion_pago(id);
CREATE INDEX ix_aplicacion_devolucion ON aplicacion_pago (devolucion_pago_id, id)
    WHERE devolucion_pago_id IS NOT NULL;

ALTER TABLE movimiento_financiero
    ADD COLUMN devolucion_pago_id BIGINT REFERENCES devolucion_pago(id);
CREATE UNIQUE INDEX ux_movimiento_devolucion
    ON movimiento_financiero (devolucion_pago_id)
    WHERE devolucion_pago_id IS NOT NULL;

ALTER TABLE movimiento_financiero
    ADD CONSTRAINT chk_movimiento_devolucion
    CHECK (
        (clase = 'DEVOLUCION' AND direccion = 'EGRESO' AND devolucion_pago_id IS NOT NULL
            AND pago_id IS NULL AND transferencia_id IS NULL AND reversa_de_id IS NULL)
        OR (clase <> 'DEVOLUCION' AND devolucion_pago_id IS NULL)
    );

INSERT INTO permiso (codigo, descripcion)
VALUES ('PAGO_DEVOLVER', 'Permite ejecutar devoluciones de pagos validados y publicar su egreso')
ON CONFLICT DO NOTHING;

INSERT INTO motivo_financiero (institucion_id, codigo, nombre, naturaleza, categoria)
SELECT i.id, 'DEVOLUCION_PAGO', 'Devolución de pago', 'EGRESO', 'DEVOLUCIONES'
FROM institucion i
ON CONFLICT DO NOTHING;
