CREATE TABLE reversion_financiera (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    tipo VARCHAR(20) NOT NULL,
    movimiento_origen_id BIGINT REFERENCES movimiento_financiero(id),
    transferencia_origen_id BIGINT REFERENCES transferencia_cuenta(id),
    fecha TIMESTAMPTZ NOT NULL,
    motivo VARCHAR(2000) NOT NULL,
    autorizado_por_id BIGINT NOT NULL REFERENCES usuario(id),
    clave_idempotencia VARCHAR(120) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_reversion_idempotencia UNIQUE (institucion_id, clave_idempotencia),
    CONSTRAINT ck_reversion_tipo CHECK (tipo IN ('MOVIMIENTO_MANUAL', 'TRANSFERENCIA')),
    CONSTRAINT ck_reversion_objetivo CHECK (
        (tipo = 'MOVIMIENTO_MANUAL' AND movimiento_origen_id IS NOT NULL AND transferencia_origen_id IS NULL)
        OR (tipo = 'TRANSFERENCIA' AND movimiento_origen_id IS NULL AND transferencia_origen_id IS NOT NULL)
    ),
    CONSTRAINT ck_reversion_motivo CHECK (btrim(motivo) <> ''),
    CONSTRAINT ck_reversion_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_reversion_movimiento_origen
    ON reversion_financiera (movimiento_origen_id) WHERE movimiento_origen_id IS NOT NULL;
CREATE UNIQUE INDEX ux_reversion_transferencia_origen
    ON reversion_financiera (transferencia_origen_id) WHERE transferencia_origen_id IS NOT NULL;
CREATE INDEX ix_reversion_institucion_fecha
    ON reversion_financiera (institucion_id, fecha DESC, id DESC);

ALTER TABLE movimiento_financiero
    ADD COLUMN reversion_financiera_id BIGINT REFERENCES reversion_financiera(id);
CREATE INDEX ix_movimiento_reversion ON movimiento_financiero (reversion_financiera_id, id)
    WHERE reversion_financiera_id IS NOT NULL;

ALTER TABLE movimiento_financiero
    ADD CONSTRAINT chk_movimiento_reverso_trazable
    CHECK (
        (clase = 'REVERSO' AND reversa_de_id IS NOT NULL AND reversion_financiera_id IS NOT NULL
            AND pago_id IS NULL AND transferencia_id IS NULL AND devolucion_pago_id IS NULL)
        OR (clase <> 'REVERSO' AND reversion_financiera_id IS NULL)
    );

INSERT INTO permiso (codigo, descripcion)
VALUES ('MOVIMIENTO_FINANCIERO_REVERTIR',
        'Permite revertir operaciones manuales y transferencias con movimientos compensatorios')
ON CONFLICT DO NOTHING;
