CREATE TABLE corte_caja (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    cuenta_id BIGINT NOT NULL REFERENCES cuenta_financiera(id),
    estado VARCHAR(10) NOT NULL DEFAULT 'ABIERTO',
    abierto_en TIMESTAMPTZ NOT NULL,
    abierto_por_id BIGINT NOT NULL REFERENCES usuario(id),
    secuencia_inicial BIGINT NOT NULL,
    saldo_inicial_sistema NUMERIC(19,2) NOT NULL,
    observaciones_apertura VARCHAR(2000),
    clave_apertura VARCHAR(120) NOT NULL,
    cerrado_en TIMESTAMPTZ,
    cerrado_por_id BIGINT REFERENCES usuario(id),
    secuencia_final BIGINT,
    movimientos_contabilizados BIGINT,
    total_ingresos NUMERIC(19,2),
    total_egresos NUMERIC(19,2),
    saldo_esperado NUMERIC(19,2),
    efectivo_declarado NUMERIC(19,2),
    diferencia NUMERIC(19,2),
    justificacion_diferencia VARCHAR(2000),
    observaciones_cierre VARCHAR(2000),
    clave_cierre VARCHAR(120),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_corte_apertura UNIQUE (institucion_id, clave_apertura),
    CONSTRAINT ck_corte_estado CHECK (estado IN ('ABIERTO', 'CERRADO')),
    CONSTRAINT ck_corte_secuencia_inicial CHECK (secuencia_inicial >= 0),
    CONSTRAINT ck_corte_saldo_inicial CHECK (saldo_inicial_sistema >= 0),
    CONSTRAINT ck_corte_cierre CHECK (
        (estado = 'ABIERTO' AND cerrado_en IS NULL AND cerrado_por_id IS NULL
            AND secuencia_final IS NULL AND movimientos_contabilizados IS NULL
            AND total_ingresos IS NULL AND total_egresos IS NULL
            AND saldo_esperado IS NULL AND efectivo_declarado IS NULL
            AND diferencia IS NULL AND clave_cierre IS NULL)
        OR (estado = 'CERRADO' AND cerrado_en IS NOT NULL AND cerrado_por_id IS NOT NULL
            AND secuencia_final IS NOT NULL AND secuencia_final >= secuencia_inicial
            AND movimientos_contabilizados IS NOT NULL AND movimientos_contabilizados >= 0
            AND total_ingresos IS NOT NULL AND total_ingresos >= 0
            AND total_egresos IS NOT NULL AND total_egresos >= 0
            AND saldo_esperado IS NOT NULL AND saldo_esperado >= 0
            AND efectivo_declarado IS NOT NULL AND efectivo_declarado >= 0
            AND diferencia IS NOT NULL AND clave_cierre IS NOT NULL
            AND cerrado_en >= abierto_en
            AND (diferencia = 0 OR btrim(coalesce(justificacion_diferencia, '')) <> ''))
    ),
    CONSTRAINT ck_corte_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_corte_caja_abierto
    ON corte_caja (cuenta_id) WHERE estado = 'ABIERTO';
CREATE UNIQUE INDEX ux_corte_clave_cierre
    ON corte_caja (institucion_id, clave_cierre) WHERE clave_cierre IS NOT NULL;
CREATE INDEX ix_corte_institucion_apertura
    ON corte_caja (institucion_id, abierto_en DESC, id DESC);
CREATE INDEX ix_corte_cuenta_apertura
    ON corte_caja (cuenta_id, abierto_en DESC, id DESC);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('CORTE_CAJA_LEER', 'Permite consultar cortes de caja y sus diferencias'),
    ('CORTE_CAJA_ADMINISTRAR', 'Permite abrir y cerrar cortes de caja')
ON CONFLICT DO NOTHING;
