CREATE TABLE evento_escolar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    ciclo_escolar_id BIGINT NOT NULL REFERENCES ciclo_escolar(id),
    plantel_id BIGINT REFERENCES plantel(id),
    titulo VARCHAR(200) NOT NULL,
    ubicacion VARCHAR(250) NOT NULL,
    descripcion TEXT,
    inicio_en TIMESTAMPTZ NOT NULL,
    fin_en TIMESTAMPTZ NOT NULL,
    tipo VARCHAR(15) NOT NULL,
    estado VARCHAR(12) NOT NULL DEFAULT 'BORRADOR',
    alcance VARCHAR(12) NOT NULL,
    publicado_en TIMESTAMPTZ,
    cancelado_en TIMESTAMPTZ,
    motivo_cancelacion VARCHAR(2000),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_evento_titulo CHECK (btrim(titulo) <> ''),
    CONSTRAINT ck_evento_ubicacion CHECK (btrim(ubicacion) <> ''),
    CONSTRAINT ck_evento_fechas CHECK (fin_en >= inicio_en),
    CONSTRAINT ck_evento_tipo CHECK (tipo IN ('JUNTA','FESTIVAL','SUSPENSION','ACTIVIDAD','OTRO')),
    CONSTRAINT ck_evento_estado CHECK (estado IN ('BORRADOR','PUBLICADO','CANCELADO')),
    CONSTRAINT ck_evento_alcance CHECK (alcance IN ('INSTITUCION','PLANTEL','SELECCION')),
    CONSTRAINT ck_evento_plantel CHECK (
        (alcance = 'INSTITUCION' AND plantel_id IS NULL)
        OR alcance = 'SELECCION'
        OR (alcance = 'PLANTEL' AND plantel_id IS NOT NULL)
    ),
    CONSTRAINT ck_evento_publicacion CHECK (
        (estado = 'BORRADOR' AND publicado_en IS NULL AND cancelado_en IS NULL AND motivo_cancelacion IS NULL)
        OR (estado = 'PUBLICADO' AND publicado_en IS NOT NULL AND cancelado_en IS NULL AND motivo_cancelacion IS NULL)
        OR (estado = 'CANCELADO' AND cancelado_en IS NOT NULL
            AND btrim(coalesce(motivo_cancelacion, '')) <> '')
    ),
    CONSTRAINT ck_evento_version CHECK (version >= 0)
);

CREATE TABLE destinatario_evento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evento_id BIGINT NOT NULL REFERENCES evento_escolar(id),
    nivel_educativo_id BIGINT REFERENCES nivel_educativo(id),
    grado_id BIGINT REFERENCES grado(id),
    grupo_id BIGINT REFERENCES grupo(id),
    alumno_id BIGINT REFERENCES alumno(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_destinatario_evento_un_tipo CHECK (
        num_nonnulls(nivel_educativo_id, grado_id, grupo_id, alumno_id) = 1
    ),
    CONSTRAINT ck_destinatario_evento_version CHECK (version >= 0)
);

CREATE INDEX ix_evento_institucion_inicio
    ON evento_escolar (institucion_id, inicio_en DESC, id DESC);
CREATE INDEX ix_evento_plantel_inicio
    ON evento_escolar (plantel_id, inicio_en DESC, id DESC) WHERE plantel_id IS NOT NULL;
CREATE INDEX ix_evento_ciclo ON evento_escolar (ciclo_escolar_id);
CREATE INDEX ix_destinatario_evento_evento ON destinatario_evento (evento_id);
CREATE INDEX ix_destinatario_evento_nivel ON destinatario_evento (nivel_educativo_id) WHERE nivel_educativo_id IS NOT NULL;
CREATE INDEX ix_destinatario_evento_grado ON destinatario_evento (grado_id) WHERE grado_id IS NOT NULL;
CREATE INDEX ix_destinatario_evento_grupo ON destinatario_evento (grupo_id) WHERE grupo_id IS NOT NULL;
CREATE INDEX ix_destinatario_evento_alumno ON destinatario_evento (alumno_id) WHERE alumno_id IS NOT NULL;
CREATE UNIQUE INDEX ux_destinatario_evento_nivel ON destinatario_evento (evento_id, nivel_educativo_id) WHERE nivel_educativo_id IS NOT NULL;
CREATE UNIQUE INDEX ux_destinatario_evento_grado ON destinatario_evento (evento_id, grado_id) WHERE grado_id IS NOT NULL;
CREATE UNIQUE INDEX ux_destinatario_evento_grupo ON destinatario_evento (evento_id, grupo_id) WHERE grupo_id IS NOT NULL;
CREATE UNIQUE INDEX ux_destinatario_evento_alumno ON destinatario_evento (evento_id, alumno_id) WHERE alumno_id IS NOT NULL;

CREATE INDEX ix_nivel_evento_busqueda ON nivel_educativo
    USING gin ((lower(codigo || ' ' || nombre)) gin_trgm_ops);
CREATE INDEX ix_grado_evento_busqueda ON grado
    USING gin ((lower(codigo || ' ' || nombre)) gin_trgm_ops);
CREATE INDEX ix_grupo_evento_busqueda ON grupo
    USING gin ((lower(coalesce(codigo, '') || ' ' || nombre || ' ' || turno)) gin_trgm_ops);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('EVENTO_ESCOLAR_LEER', 'Consultar eventos escolares y sus destinatarios'),
    ('EVENTO_ESCOLAR_ADMINISTRAR', 'Crear, publicar y cancelar eventos escolares')
ON CONFLICT DO NOTHING;
