CREATE TABLE aviso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    plantel_id BIGINT REFERENCES plantel(id),
    titulo VARCHAR(200) NOT NULL,
    contenido TEXT NOT NULL,
    estado VARCHAR(10) NOT NULL DEFAULT 'BORRADOR',
    publicado_en TIMESTAMPTZ,
    expira_en TIMESTAMPTZ,
    retirado_en TIMESTAMPTZ,
    motivo_retiro VARCHAR(1000),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_aviso_titulo CHECK (btrim(titulo) <> ''),
    CONSTRAINT ck_aviso_contenido CHECK (btrim(contenido) <> ''),
    CONSTRAINT ck_aviso_estado CHECK (estado IN ('BORRADOR','PUBLICADO','RETIRADO')),
    CONSTRAINT ck_aviso_flujo CHECK (
        (estado='BORRADOR' AND publicado_en IS NULL AND retirado_en IS NULL AND motivo_retiro IS NULL)
        OR (estado='PUBLICADO' AND publicado_en IS NOT NULL AND retirado_en IS NULL AND motivo_retiro IS NULL)
        OR (estado='RETIRADO' AND publicado_en IS NOT NULL AND retirado_en IS NOT NULL
            AND btrim(coalesce(motivo_retiro,'')) <> '')
    ),
    CONSTRAINT ck_aviso_vencimiento CHECK (expira_en IS NULL OR publicado_en IS NULL OR expira_en > publicado_en),
    CONSTRAINT ck_aviso_version CHECK (version >= 0)
);

CREATE INDEX ix_aviso_institucion_estado_publicacion
    ON aviso (institucion_id, estado, publicado_en DESC, id DESC);
CREATE INDEX ix_aviso_plantel_estado_publicacion
    ON aviso (plantel_id, estado, publicado_en DESC, id DESC) WHERE plantel_id IS NOT NULL;
CREATE INDEX ix_aviso_portal_vigente
    ON aviso (institucion_id, publicado_en DESC, id DESC)
    WHERE estado='PUBLICADO';

INSERT INTO permiso (codigo, descripcion) VALUES
    ('AVISO_LEER', 'Consultar avisos escolares'),
    ('AVISO_ADMINISTRAR', 'Crear, publicar y retirar avisos escolares')
ON CONFLICT DO NOTHING;
