CREATE TABLE notificacion_usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL REFERENCES usuario(id),
    tipo VARCHAR(10) NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    mensaje VARCHAR(1000) NOT NULL,
    evento_id BIGINT REFERENCES evento_escolar(id),
    aviso_id BIGINT REFERENCES aviso(id),
    leida_en TIMESTAMPTZ,
    clave_deduplicacion VARCHAR(100) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_notificacion_tipo CHECK (tipo IN ('EVENTO','AVISO')),
    CONSTRAINT ck_notificacion_origen CHECK (
        (tipo='EVENTO' AND evento_id IS NOT NULL AND aviso_id IS NULL)
        OR (tipo='AVISO' AND aviso_id IS NOT NULL AND evento_id IS NULL)
    ),
    CONSTRAINT ck_notificacion_titulo CHECK (btrim(titulo) <> ''),
    CONSTRAINT ck_notificacion_mensaje CHECK (btrim(mensaje) <> ''),
    CONSTRAINT ck_notificacion_version CHECK (version >= 0),
    CONSTRAINT ux_notificacion_usuario_clave UNIQUE (usuario_id, clave_deduplicacion)
);

CREATE INDEX ix_notificacion_usuario_fecha
    ON notificacion_usuario (usuario_id, creado_en DESC, id DESC);
CREATE INDEX ix_notificacion_usuario_pendiente
    ON notificacion_usuario (usuario_id, creado_en DESC, id DESC) WHERE leida_en IS NULL;
CREATE INDEX ix_notificacion_evento ON notificacion_usuario (evento_id) WHERE evento_id IS NOT NULL;
CREATE INDEX ix_notificacion_aviso ON notificacion_usuario (aviso_id) WHERE aviso_id IS NOT NULL;
