CREATE TABLE permiso (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo              VARCHAR(80) NOT NULL,
    descripcion         VARCHAR(250) NOT NULL,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_permiso_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_permiso_descripcion_no_vacia CHECK (btrim(descripcion) <> ''),
    CONSTRAINT ck_permiso_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_permiso_codigo_normalizado ON permiso (upper(btrim(codigo)));

CREATE TABLE rol (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    codigo              VARCHAR(50) NOT NULL,
    nombre              VARCHAR(150) NOT NULL,
    descripcion         TEXT,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_rol_codigo_no_vacio CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_rol_nombre_no_vacio CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_rol_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_rol_institucion_codigo
    ON rol (institucion_id, upper(btrim(codigo)));
CREATE INDEX ix_rol_institucion ON rol (institucion_id);

CREATE TABLE usuario (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    username            VARCHAR(80) NOT NULL,
    email               VARCHAR(254) NOT NULL,
    password_hash       VARCHAR(255),
    estado              VARCHAR(20) NOT NULL,
    ultimo_acceso_en    TIMESTAMPTZ,
    bloqueo_hasta       TIMESTAMPTZ,
    intentos_fallidos   INTEGER NOT NULL DEFAULT 0,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_usuario_username_no_vacio CHECK (btrim(username) <> ''),
    CONSTRAINT ck_usuario_email_no_vacio CHECK (btrim(email) <> ''),
    CONSTRAINT ck_usuario_estado CHECK (estado IN ('INVITADO', 'ACTIVO', 'BLOQUEADO', 'INACTIVO')),
    CONSTRAINT ck_usuario_intentos CHECK (intentos_fallidos >= 0),
    CONSTRAINT ck_usuario_password_activo CHECK (estado <> 'ACTIVO' OR password_hash IS NOT NULL),
    CONSTRAINT ck_usuario_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_usuario_institucion_username
    ON usuario (institucion_id, lower(btrim(username)));
CREATE UNIQUE INDEX ux_usuario_institucion_email
    ON usuario (institucion_id, lower(btrim(email)));
CREATE INDEX ix_usuario_institucion_estado ON usuario (institucion_id, estado);

CREATE TABLE rol_permiso (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rol_id              BIGINT NOT NULL REFERENCES rol(id),
    permiso_id          BIGINT NOT NULL REFERENCES permiso(id),
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_rol_permiso UNIQUE (rol_id, permiso_id),
    CONSTRAINT ck_rol_permiso_version CHECK (version >= 0)
);

CREATE INDEX ix_rol_permiso_permiso ON rol_permiso (permiso_id);

CREATE TABLE usuario_rol (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          BIGINT NOT NULL REFERENCES usuario(id),
    rol_id              BIGINT NOT NULL REFERENCES rol(id),
    alcance             VARCHAR(25) NOT NULL,
    plantel_id          BIGINT REFERENCES plantel(id),
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_usuario_rol_alcance CHECK (alcance IN ('INSTITUCION', 'PLANTEL', 'VINCULOS_TUTOR')),
    CONSTRAINT ck_usuario_rol_plantel CHECK (
        (alcance = 'PLANTEL' AND plantel_id IS NOT NULL)
        OR (alcance <> 'PLANTEL' AND plantel_id IS NULL)
    ),
    CONSTRAINT ck_usuario_rol_version CHECK (version >= 0),
    CONSTRAINT uq_usuario_rol UNIQUE NULLS NOT DISTINCT
        (usuario_id, rol_id, alcance, plantel_id)
);

CREATE INDEX ix_usuario_rol_rol ON usuario_rol (rol_id);
CREATE INDEX ix_usuario_rol_plantel ON usuario_rol (plantel_id) WHERE plantel_id IS NOT NULL;

CREATE TABLE invitacion_usuario (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          BIGINT NOT NULL REFERENCES usuario(id),
    token_hash          VARCHAR(64) NOT NULL,
    expira_en           TIMESTAMPTZ NOT NULL,
    usado_en            TIMESTAMPTZ,
    revocado_en         TIMESTAMPTZ,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_invitacion_token_hash CHECK (token_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_invitacion_fechas CHECK (expira_en > creado_en),
    CONSTRAINT ck_invitacion_resolucion CHECK (usado_en IS NULL OR revocado_en IS NULL),
    CONSTRAINT ck_invitacion_version CHECK (version >= 0),
    CONSTRAINT uq_invitacion_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_invitacion_usuario ON invitacion_usuario (usuario_id);
CREATE UNIQUE INDEX ux_invitacion_usuario_vigente
    ON invitacion_usuario (usuario_id)
    WHERE usado_en IS NULL AND revocado_en IS NULL;

INSERT INTO permiso (codigo, descripcion) VALUES
    ('INSTITUCION_LEER', 'Consultar instituciones'),
    ('INSTITUCION_ADMINISTRAR', 'Crear y modificar instituciones'),
    ('PLANTEL_LEER', 'Consultar planteles'),
    ('PLANTEL_ADMINISTRAR', 'Crear y modificar planteles'),
    ('NIVEL_LEER', 'Consultar niveles educativos'),
    ('NIVEL_ADMINISTRAR', 'Crear y modificar niveles educativos'),
    ('OFERTA_LEER', 'Consultar oferta educativa'),
    ('OFERTA_ADMINISTRAR', 'Crear y modificar oferta educativa'),
    ('GRADO_LEER', 'Consultar grados'),
    ('GRADO_ADMINISTRAR', 'Crear y modificar grados'),
    ('CICLO_LEER', 'Consultar ciclos escolares'),
    ('CICLO_ADMINISTRAR', 'Crear y modificar ciclos escolares'),
    ('PERIODO_LEER', 'Consultar periodos académicos'),
    ('PERIODO_ADMINISTRAR', 'Crear y modificar periodos académicos'),
    ('GRUPO_LEER', 'Consultar grupos'),
    ('GRUPO_ADMINISTRAR', 'Crear y modificar grupos'),
    ('USUARIO_ADMINISTRAR', 'Administrar usuarios y sus asignaciones'),
    ('ROL_ADMINISTRAR', 'Administrar roles y permisos');
