CREATE TABLE auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    usuario_actor_id BIGINT REFERENCES usuario(id),
    actor_sistema VARCHAR(80),
    accion VARCHAR(60) NOT NULL,
    tipo_entidad VARCHAR(80) NOT NULL,
    entidad_id VARCHAR(100) NOT NULL,
    ocurrido_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo TEXT,
    cambios TEXT,
    correlacion_id VARCHAR(64) NOT NULL,
    CONSTRAINT ck_auditoria_actor CHECK (
        (usuario_actor_id IS NOT NULL AND actor_sistema IS NULL)
        OR (usuario_actor_id IS NULL AND btrim(actor_sistema) <> '')
    ),
    CONSTRAINT ck_auditoria_accion CHECK (btrim(accion) <> ''),
    CONSTRAINT ck_auditoria_tipo CHECK (btrim(tipo_entidad) <> ''),
    CONSTRAINT ck_auditoria_entidad CHECK (btrim(entidad_id) <> ''),
    CONSTRAINT ck_auditoria_correlacion CHECK (btrim(correlacion_id) <> '')
);

CREATE INDEX ix_auditoria_institucion_fecha
    ON auditoria (institucion_id, ocurrido_en DESC, id DESC);
CREATE INDEX ix_auditoria_entidad
    ON auditoria (institucion_id, tipo_entidad, entidad_id, ocurrido_en DESC);
CREATE INDEX ix_auditoria_actor
    ON auditoria (usuario_actor_id, ocurrido_en DESC) WHERE usuario_actor_id IS NOT NULL;
CREATE INDEX ix_auditoria_correlacion ON auditoria (correlacion_id);

CREATE FUNCTION impedir_modificacion_auditoria() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'La bitácora de auditoría es inmutable';
END;
$$;

CREATE TRIGGER tg_auditoria_inmutable
    BEFORE UPDATE OR DELETE ON auditoria
    FOR EACH ROW EXECUTE FUNCTION impedir_modificacion_auditoria();

INSERT INTO permiso (codigo, descripcion) VALUES
    ('AUDITORIA_CONSULTAR', 'Consultar y exportar la bitácora inmutable de auditoría');
