CREATE TABLE retiro_fondo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    cuenta_id BIGINT NOT NULL REFERENCES cuenta_financiera(id),
    plantel_operacion_id BIGINT REFERENCES plantel(id),
    movimiento_id BIGINT NOT NULL UNIQUE REFERENCES movimiento_financiero(id),
    autorizado_por_id BIGINT NOT NULL REFERENCES usuario(id),
    motivo_financiero_id BIGINT NOT NULL REFERENCES motivo_financiero(id),
    fecha_operacion TIMESTAMPTZ NOT NULL,
    monto NUMERIC(19,2) NOT NULL CHECK (monto > 0),
    beneficiario VARCHAR(180) NOT NULL,
    concepto VARCHAR(250) NOT NULL,
    referencia VARCHAR(150) NOT NULL,
    observaciones VARCHAR(500),
    clave_idempotencia VARCHAR(100) NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_retiro_fondo_clave UNIQUE (institucion_id, clave_idempotencia),
    CONSTRAINT ck_retiro_fondo_beneficiario CHECK (length(trim(beneficiario)) > 0),
    CONSTRAINT ck_retiro_fondo_concepto CHECK (length(trim(concepto)) > 0),
    CONSTRAINT ck_retiro_fondo_referencia CHECK (length(trim(referencia)) > 0),
    CONSTRAINT ck_retiro_fondo_version CHECK (version >= 0)
);

CREATE INDEX ix_retiro_fondo_institucion_fecha
    ON retiro_fondo (institucion_id, fecha_operacion DESC, id DESC);
CREATE INDEX ix_retiro_fondo_cuenta_fecha
    ON retiro_fondo (cuenta_id, fecha_operacion DESC, id DESC);
CREATE INDEX ix_retiro_fondo_plantel_fecha
    ON retiro_fondo (plantel_operacion_id, fecha_operacion DESC, id DESC);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('RETIRO_FONDO_LEER', 'Consultar retiros externos de fondos y exportar sus filtros a Excel'),
    ('RETIRO_FONDO_REGISTRAR', 'Registrar retiros externos de fondos con destinatario y referencia');
