CREATE TABLE tutor_identificacion (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tutor_id              BIGINT NOT NULL REFERENCES tutor(id),
    archivo_id            BIGINT NOT NULL REFERENCES archivo(id),
    tipo                  VARCHAR(30) NOT NULL,
    retirada_en           TIMESTAMPTZ,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id         BIGINT,
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id    BIGINT,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_tutor_identificacion_archivo UNIQUE (archivo_id),
    CONSTRAINT ck_tutor_identificacion_tipo CHECK (
        tipo IN ('INE', 'LICENCIA_CONDUCIR', 'PASAPORTE', 'OTRA_IDENTIFICACION_OFICIAL')
    ),
    CONSTRAINT ck_tutor_identificacion_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_tutor_identificacion_actual
    ON tutor_identificacion (tutor_id) WHERE retirada_en IS NULL;

CREATE INDEX ix_tutor_identificacion_historial
    ON tutor_identificacion (tutor_id, creado_en DESC);
