CREATE TABLE alumno_documento (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id             BIGINT NOT NULL REFERENCES alumno(id),
    archivo_id            BIGINT NOT NULL REFERENCES archivo(id),
    tipo                  VARCHAR(40) NOT NULL,
    descripcion           VARCHAR(500),
    fecha_documento       DATE,
    vigente_hasta         DATE,
    retirado_en           TIMESTAMPTZ,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id         BIGINT,
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id    BIGINT,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_alumno_documento_archivo UNIQUE (archivo_id),
    CONSTRAINT ck_alumno_documento_tipo CHECK (tipo IN (
        'ACTA_NACIMIENTO', 'CURP', 'COMPROBANTE_DOMICILIO',
        'CONSTANCIA_CERTIFICADO', 'AUTORIZACION', 'DOCUMENTO_MEDICO', 'OTRO'
    )),
    CONSTRAINT ck_alumno_documento_vigencia CHECK (
        vigente_hasta IS NULL OR fecha_documento IS NULL OR vigente_hasta >= fecha_documento
    ),
    CONSTRAINT ck_alumno_documento_version CHECK (version >= 0)
);

CREATE INDEX ix_alumno_documento_actual
    ON alumno_documento (alumno_id, tipo, creado_en DESC) WHERE retirado_en IS NULL;

CREATE INDEX ix_alumno_documento_historial
    ON alumno_documento (alumno_id, creado_en DESC);

CREATE TABLE ficha_medica_alumno (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id                       BIGINT NOT NULL REFERENCES alumno(id),
    tipo_sanguineo                  VARCHAR(20) NOT NULL DEFAULT 'DESCONOCIDO',
    alergias                        TEXT,
    padecimientos                   TEXT,
    medicamentos                    TEXT,
    discapacidad_necesidades        TEXT,
    restricciones_fisicas           TEXT,
    restricciones_alimentarias      TEXT,
    servicio_medico                 VARCHAR(150),
    numero_afiliacion               VARCHAR(100),
    medico_tratante                 VARCHAR(180),
    contacto_emergencia             VARCHAR(180),
    telefono_emergencia             VARCHAR(30),
    observaciones                   TEXT,
    autoriza_atencion_emergencia    BOOLEAN NOT NULL DEFAULT FALSE,
    creado_en                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id                   BIGINT,
    actualizado_en                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id              BIGINT,
    version                         BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_ficha_medica_alumno UNIQUE (alumno_id),
    CONSTRAINT ck_ficha_medica_tipo_sanguineo CHECK (tipo_sanguineo IN (
        'DESCONOCIDO', 'A_POSITIVO', 'A_NEGATIVO', 'B_POSITIVO', 'B_NEGATIVO',
        'AB_POSITIVO', 'AB_NEGATIVO', 'O_POSITIVO', 'O_NEGATIVO'
    )),
    CONSTRAINT ck_ficha_medica_version CHECK (version >= 0)
);

