CREATE TABLE materia (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id        BIGINT NOT NULL REFERENCES institucion(id),
    codigo                VARCHAR(50) NOT NULL,
    nombre                VARCHAR(150) NOT NULL,
    descripcion           TEXT,
    activo                BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id         BIGINT,
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id    BIGINT,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_materia_institucion_codigo UNIQUE (institucion_id, codigo),
    CONSTRAINT ck_materia_codigo CHECK (btrim(codigo) <> ''),
    CONSTRAINT ck_materia_nombre CHECK (btrim(nombre) <> ''),
    CONSTRAINT ck_materia_version CHECK (version >= 0)
);

CREATE TABLE materia_grado (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    materia_id            BIGINT NOT NULL REFERENCES materia(id),
    grado_id              BIGINT NOT NULL REFERENCES grado(id),
    tipo_evaluacion       VARCHAR(15) NOT NULL,
    escala_minima         NUMERIC(7,2),
    escala_maxima         NUMERIC(7,2),
    minima_aprobatoria    NUMERIC(7,2),
    decimales             INTEGER NOT NULL DEFAULT 0,
    orden                 INTEGER NOT NULL,
    horas_semanales       NUMERIC(5,2),
    incluir_boleta        BOOLEAN NOT NULL DEFAULT TRUE,
    activo                BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id         BIGINT,
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id    BIGINT,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_materia_grado UNIQUE (materia_id, grado_id),
    CONSTRAINT ck_materia_grado_tipo CHECK (tipo_evaluacion IN ('NUMERICA', 'CUALITATIVA')),
    CONSTRAINT ck_materia_grado_escala CHECK (
        (tipo_evaluacion = 'NUMERICA'
            AND escala_minima IS NOT NULL AND escala_maxima IS NOT NULL
            AND minima_aprobatoria IS NOT NULL
            AND escala_minima < escala_maxima
            AND minima_aprobatoria BETWEEN escala_minima AND escala_maxima)
        OR
        (tipo_evaluacion = 'CUALITATIVA'
            AND escala_minima IS NULL AND escala_maxima IS NULL
            AND minima_aprobatoria IS NULL)
    ),
    CONSTRAINT ck_materia_grado_decimales CHECK (decimales BETWEEN 0 AND 2),
    CONSTRAINT ck_materia_grado_orden CHECK (orden > 0),
    CONSTRAINT ck_materia_grado_horas CHECK (horas_semanales IS NULL OR horas_semanales > 0),
    CONSTRAINT ck_materia_grado_version CHECK (version >= 0)
);

CREATE INDEX ix_materia_institucion_nombre ON materia (institucion_id, nombre, id);
CREATE INDEX ix_materia_grado_grado ON materia_grado (grado_id, orden, id) WHERE activo = TRUE;
CREATE UNIQUE INDEX ux_materia_grado_orden_activo
    ON materia_grado (grado_id, orden) WHERE activo = TRUE;
CREATE INDEX ix_materia_grado_materia ON materia_grado (materia_id, activo, orden);
CREATE INDEX ix_materia_busqueda ON materia
    USING gin ((lower(codigo || ' ' || nombre || ' ' || coalesce(descripcion, ''))) gin_trgm_ops);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('MATERIA_LEER', 'Consultar materias y planes por grado'),
    ('MATERIA_ADMINISTRAR', 'Crear y administrar materias y planes por grado')
ON CONFLICT DO NOTHING;
