CREATE TABLE calificacion (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id        BIGINT NOT NULL REFERENCES inscripcion(id),
    materia_grado_id      BIGINT NOT NULL REFERENCES materia_grado(id),
    periodo_academico_id  BIGINT NOT NULL REFERENCES periodo_academico(id),
    tipo_evaluacion       VARCHAR(15) NOT NULL,
    escala_minima         NUMERIC(7,2),
    escala_maxima         NUMERIC(7,2),
    minima_aprobatoria    NUMERIC(7,2),
    decimales             INTEGER NOT NULL DEFAULT 0,
    valor_numerico        NUMERIC(7,2),
    valor_cualitativo     VARCHAR(100),
    observaciones         VARCHAR(1000),
    estado                VARCHAR(15) NOT NULL DEFAULT 'BORRADOR',
    publicado_en          TIMESTAMPTZ,
    publicado_por_id      BIGINT REFERENCES usuario(id),
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id         BIGINT,
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id    BIGINT,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_calificacion_registro UNIQUE
        (inscripcion_id, materia_grado_id, periodo_academico_id),
    CONSTRAINT ck_calificacion_tipo CHECK (tipo_evaluacion IN ('NUMERICA', 'CUALITATIVA')),
    CONSTRAINT ck_calificacion_estado CHECK (estado IN ('BORRADOR', 'PUBLICADA')),
    CONSTRAINT ck_calificacion_decimales CHECK (decimales BETWEEN 0 AND 2),
    CONSTRAINT ck_calificacion_escala CHECK (
        (tipo_evaluacion = 'NUMERICA'
            AND escala_minima IS NOT NULL AND escala_maxima IS NOT NULL
            AND minima_aprobatoria IS NOT NULL AND escala_minima < escala_maxima
            AND minima_aprobatoria BETWEEN escala_minima AND escala_maxima
            AND valor_cualitativo IS NULL)
        OR
        (tipo_evaluacion = 'CUALITATIVA'
            AND escala_minima IS NULL AND escala_maxima IS NULL
            AND minima_aprobatoria IS NULL AND valor_numerico IS NULL)
    ),
    CONSTRAINT ck_calificacion_valor_numerico CHECK (
        valor_numerico IS NULL OR valor_numerico BETWEEN escala_minima AND escala_maxima),
    CONSTRAINT ck_calificacion_publicacion CHECK (
        (estado = 'BORRADOR' AND publicado_en IS NULL AND publicado_por_id IS NULL)
        OR
        (estado = 'PUBLICADA' AND publicado_en IS NOT NULL
            AND ((tipo_evaluacion = 'NUMERICA' AND valor_numerico IS NOT NULL)
              OR (tipo_evaluacion = 'CUALITATIVA' AND btrim(valor_cualitativo) <> '')))
    ),
    CONSTRAINT ck_calificacion_version CHECK (version >= 0)
);

CREATE INDEX ix_calificacion_inscripcion ON calificacion (inscripcion_id, periodo_academico_id);
CREATE INDEX ix_calificacion_captura ON calificacion (materia_grado_id, periodo_academico_id, estado);
CREATE INDEX ix_calificacion_publicada_portal
    ON calificacion (inscripcion_id, periodo_academico_id, materia_grado_id)
    WHERE estado = 'PUBLICADA';

INSERT INTO permiso (codigo, descripcion) VALUES
    ('CALIFICACION_LEER', 'Consultar calificaciones académicas'),
    ('CALIFICACION_ADMINISTRAR', 'Capturar, publicar y reabrir calificaciones')
ON CONFLICT DO NOTHING;
