CREATE TABLE asistencia (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inscripcion_id  BIGINT NOT NULL REFERENCES inscripcion(id),
    grupo_id        BIGINT NOT NULL REFERENCES grupo(id),
    fecha           DATE NOT NULL,
    estado          VARCHAR(15) NOT NULL,
    observaciones   VARCHAR(1000),
    creado_en       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id   BIGINT,
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version         BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_asistencia_inscripcion_fecha UNIQUE (inscripcion_id, fecha),
    CONSTRAINT ck_asistencia_estado CHECK (estado IN ('PRESENTE','AUSENTE','RETARDO','JUSTIFICADA')),
    CONSTRAINT ck_asistencia_observaciones CHECK (observaciones IS NULL OR btrim(observaciones) <> ''),
    CONSTRAINT ck_asistencia_version CHECK (version >= 0)
);

CREATE INDEX ix_asistencia_grupo_fecha ON asistencia (grupo_id, fecha DESC, id);
CREATE INDEX ix_asistencia_inscripcion_fecha ON asistencia (inscripcion_id, fecha DESC, id);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('ASISTENCIA_LEER', 'Consultar historial de asistencia'),
    ('ASISTENCIA_ADMINISTRAR', 'Capturar y corregir asistencia diaria')
ON CONFLICT DO NOTHING;
