CREATE EXTENSION IF NOT EXISTS btree_gist;

ALTER TABLE usuario DROP CONSTRAINT ck_usuario_tipo_cuenta;
ALTER TABLE usuario ADD CONSTRAINT ck_usuario_tipo_cuenta
    CHECK (tipo_cuenta IN ('ADMINISTRATIVO', 'PORTAL_TUTOR', 'PORTAL_MAESTRO'));

CREATE TABLE maestro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    usuario_id BIGINT UNIQUE REFERENCES usuario(id),
    numero_empleado VARCHAR(50) NOT NULL,
    nombres VARCHAR(150) NOT NULL,
    primer_apellido VARCHAR(100) NOT NULL,
    segundo_apellido VARCHAR(100),
    email VARCHAR(254) NOT NULL,
    telefono VARCHAR(30),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_maestro_institucion_numero UNIQUE (institucion_id, numero_empleado),
    CONSTRAINT ck_maestro_numero CHECK (btrim(numero_empleado) <> ''),
    CONSTRAINT ck_maestro_nombres CHECK (btrim(nombres) <> '' AND btrim(primer_apellido) <> ''),
    CONSTRAINT ck_maestro_version CHECK (version >= 0)
);

CREATE TABLE asignacion_maestro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    maestro_id BIGINT NOT NULL REFERENCES maestro(id),
    grupo_id BIGINT NOT NULL REFERENCES grupo(id),
    materia_id BIGINT NOT NULL REFERENCES materia(id),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_asignacion_maestro_inicio UNIQUE (maestro_id, grupo_id, materia_id, fecha_inicio),
    CONSTRAINT ck_asignacion_maestro_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_asignacion_maestro_version CHECK (version >= 0)
);

CREATE TABLE planeacion_semanal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    maestro_id BIGINT NOT NULL REFERENCES maestro(id),
    grupo_id BIGINT NOT NULL REFERENCES grupo(id),
    ciclo_escolar_id BIGINT NOT NULL REFERENCES ciclo_escolar(id),
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    estado VARCHAR(25) NOT NULL DEFAULT 'BORRADOR',
    numero_revision INTEGER NOT NULL DEFAULT 0,
    situacion_didactica TEXT,
    proposito TEXT NOT NULL,
    ejes_articuladores TEXT,
    conocimientos TEXT,
    habilidades TEXT,
    actitudes TEXT,
    tecnica_evaluacion TEXT,
    instrumento_evaluacion TEXT,
    recursos TEXT,
    actividades_permanentes TEXT,
    ajustes_razonables TEXT,
    observaciones TEXT,
    enviada_en TIMESTAMPTZ,
    revision_iniciada_en TIMESTAMPTZ,
    publicada_en TIMESTAMPTZ,
    publicada_por_id BIGINT REFERENCES usuario(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_planeacion_fechas CHECK (fecha_fin >= fecha_inicio AND fecha_fin <= fecha_inicio + 6),
    CONSTRAINT ck_planeacion_estado CHECK (estado IN ('BORRADOR', 'ENVIADA', 'EN_REVISION', 'REQUIERE_AJUSTES', 'PUBLICADA', 'REABIERTA', 'DESCARTADA')),
    CONSTRAINT ck_planeacion_revision CHECK (numero_revision >= 0),
    CONSTRAINT ck_planeacion_proposito CHECK (btrim(proposito) <> ''),
    CONSTRAINT ck_planeacion_version CHECK (version >= 0)
);

ALTER TABLE planeacion_semanal ADD CONSTRAINT ex_planeacion_maestro_grupo_rango
    EXCLUDE USING gist (
        maestro_id WITH =,
        grupo_id WITH =,
        daterange(fecha_inicio, fecha_fin, '[]') WITH &&
    ) WHERE (estado <> 'DESCARTADA');

CREATE TABLE planeacion_materia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planeacion_id BIGINT NOT NULL REFERENCES planeacion_semanal(id),
    materia_id BIGINT NOT NULL REFERENCES materia(id),
    orden INTEGER NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_planeacion_materia UNIQUE (planeacion_id, materia_id),
    CONSTRAINT ux_planeacion_materia_orden UNIQUE (planeacion_id, orden),
    CONSTRAINT ck_planeacion_materia_orden CHECK (orden > 0)
);

CREATE TABLE planeacion_alineacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planeacion_id BIGINT NOT NULL REFERENCES planeacion_semanal(id),
    materia_id BIGINT REFERENCES materia(id),
    campo_formativo VARCHAR(250) NOT NULL,
    contenido TEXT NOT NULL,
    proceso_desarrollo TEXT NOT NULL,
    orden INTEGER NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_planeacion_alineacion_orden UNIQUE (planeacion_id, orden),
    CONSTRAINT ck_planeacion_alineacion_texto CHECK (btrim(campo_formativo) <> '' AND btrim(contenido) <> '' AND btrim(proceso_desarrollo) <> ''),
    CONSTRAINT ck_planeacion_alineacion_orden CHECK (orden > 0)
);

CREATE TABLE planeacion_actividad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planeacion_id BIGINT NOT NULL REFERENCES planeacion_semanal(id),
    materia_id BIGINT NOT NULL REFERENCES materia(id),
    fecha DATE NOT NULL,
    titulo VARCHAR(250) NOT NULL,
    inicio TEXT NOT NULL,
    desarrollo TEXT NOT NULL,
    cierre TEXT NOT NULL,
    duracion_minutos INTEGER,
    tarea TEXT,
    observaciones TEXT,
    orden INTEGER NOT NULL,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_planeacion_actividad_orden UNIQUE (planeacion_id, orden),
    CONSTRAINT ck_planeacion_actividad_texto CHECK (btrim(titulo) <> '' AND btrim(inicio) <> '' AND btrim(desarrollo) <> '' AND btrim(cierre) <> ''),
    CONSTRAINT ck_planeacion_actividad_duracion CHECK (duracion_minutos IS NULL OR duracion_minutos > 0),
    CONSTRAINT ck_planeacion_actividad_orden CHECK (orden > 0)
);

CREATE TABLE planeacion_historial (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planeacion_id BIGINT NOT NULL REFERENCES planeacion_semanal(id),
    estado_anterior VARCHAR(25),
    estado_nuevo VARCHAR(25) NOT NULL,
    motivo TEXT,
    actor_id BIGINT REFERENCES usuario(id),
    ocurrido_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE planeacion_version_publicada (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    planeacion_id BIGINT NOT NULL REFERENCES planeacion_semanal(id),
    numero_revision INTEGER NOT NULL,
    contenido_json TEXT NOT NULL,
    publicada_en TIMESTAMPTZ NOT NULL,
    publicada_por_id BIGINT REFERENCES usuario(id),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_planeacion_version_publicada UNIQUE (planeacion_id, numero_revision),
    CONSTRAINT ck_planeacion_version_numero CHECK (numero_revision > 0)
);

CREATE INDEX ix_maestro_institucion_nombre ON maestro (institucion_id, primer_apellido, segundo_apellido, nombres, id);
CREATE INDEX ix_asignacion_maestro_vigente ON asignacion_maestro (maestro_id, grupo_id, activo, fecha_inicio, fecha_fin);
CREATE INDEX ix_asignacion_maestro_materia ON asignacion_maestro (grupo_id, materia_id, activo);
CREATE INDEX ix_planeacion_consulta ON planeacion_semanal (institucion_id, estado, fecha_inicio DESC, id DESC);
CREATE INDEX ix_planeacion_maestro ON planeacion_semanal (maestro_id, fecha_inicio DESC, id DESC);
CREATE INDEX ix_planeacion_grupo ON planeacion_semanal (grupo_id, fecha_inicio DESC, id DESC);
CREATE INDEX ix_planeacion_historial ON planeacion_historial (planeacion_id, ocurrido_en DESC, id DESC);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('MAESTRO_LEER', 'Consultar maestros y sus asignaciones'),
    ('MAESTRO_ADMINISTRAR', 'Crear y administrar maestros, cuentas y asignaciones'),
    ('PLANEACION_LEER', 'Consultar y exportar planeaciones docentes'),
    ('PLANEACION_ADMINISTRAR', 'Revisar, publicar, solicitar ajustes y reabrir planeaciones'),
    ('PORTAL_MAESTRO_ACCEDER', 'Acceder al portal privado de maestros')
ON CONFLICT DO NOTHING;
