CREATE TABLE horario_clase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    plantel_id BIGINT NOT NULL REFERENCES plantel(id),
    ciclo_escolar_id BIGINT NOT NULL REFERENCES ciclo_escolar(id),
    asignacion_maestro_id BIGINT NOT NULL REFERENCES asignacion_maestro(id),
    maestro_id BIGINT NOT NULL REFERENCES maestro(id),
    grupo_id BIGINT NOT NULL REFERENCES grupo(id),
    materia_id BIGINT NOT NULL REFERENCES materia(id),
    dia_semana SMALLINT NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    aula VARCHAR(100),
    observaciones VARCHAR(1000),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_horario_dia CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT ck_horario_horas CHECK (hora_fin > hora_inicio),
    CONSTRAINT ck_horario_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_horario_aula CHECK (aula IS NULL OR btrim(aula) <> ''),
    CONSTRAINT ck_horario_version CHECK (version >= 0)
);

ALTER TABLE horario_clase ADD CONSTRAINT ex_horario_maestro
    EXCLUDE USING gist (maestro_id WITH =, dia_semana WITH =,
        daterange(fecha_inicio, fecha_fin, '[]') WITH &&,
        tsrange(DATE '2000-01-01' + hora_inicio, DATE '2000-01-01' + hora_fin, '[)') WITH &&)
    WHERE (activo);
ALTER TABLE horario_clase ADD CONSTRAINT ex_horario_grupo
    EXCLUDE USING gist (grupo_id WITH =, dia_semana WITH =,
        daterange(fecha_inicio, fecha_fin, '[]') WITH &&,
        tsrange(DATE '2000-01-01' + hora_inicio, DATE '2000-01-01' + hora_fin, '[)') WITH &&)
    WHERE (activo);
ALTER TABLE horario_clase ADD CONSTRAINT ex_horario_aula
    EXCLUDE USING gist (plantel_id WITH =, (lower(aula)) WITH =, dia_semana WITH =,
        daterange(fecha_inicio, fecha_fin, '[]') WITH &&,
        tsrange(DATE '2000-01-01' + hora_inicio, DATE '2000-01-01' + hora_fin, '[)') WITH &&)
    WHERE (activo AND aula IS NOT NULL);

CREATE INDEX ix_horario_consulta ON horario_clase
    (institucion_id, plantel_id, ciclo_escolar_id, activo, dia_semana, hora_inicio, id);
CREATE INDEX ix_horario_maestro_consulta ON horario_clase
    (maestro_id, activo, fecha_inicio, fecha_fin, dia_semana, hora_inicio);
CREATE INDEX ix_horario_grupo_consulta ON horario_clase
    (grupo_id, activo, fecha_inicio, fecha_fin, dia_semana, hora_inicio);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('HORARIO_CLASE_LEER', 'Consultar y exportar horarios de clase'),
    ('HORARIO_CLASE_ADMINISTRAR', 'Crear, editar y desactivar horarios de clase')
ON CONFLICT DO NOTHING;
