CREATE TABLE calendario_escolar_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    ciclo_escolar_id BIGINT NOT NULL REFERENCES ciclo_escolar(id),
    plantel_id BIGINT REFERENCES plantel(id),
    nivel_educativo_id BIGINT REFERENCES nivel_educativo(id),
    tipo VARCHAR(30) NOT NULL,
    titulo VARCHAR(200) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE NOT NULL,
    hora_inicio TIME,
    hora_fin TIME,
    suspende_clases BOOLEAN NOT NULL DEFAULT FALSE,
    descripcion VARCHAR(3000),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_calendario_tipo CHECK (tipo IN ('DIA_INHABIL','VACACIONES','EVENTO_ACADEMICO','VARIACION_HORARIO')),
    CONSTRAINT ck_calendario_titulo CHECK (btrim(titulo) <> ''),
    CONSTRAINT ck_calendario_fechas CHECK (fecha_fin >= fecha_inicio),
    CONSTRAINT ck_calendario_horas CHECK ((hora_inicio IS NULL AND hora_fin IS NULL) OR (hora_inicio IS NOT NULL AND hora_fin IS NOT NULL AND hora_fin > hora_inicio)),
    CONSTRAINT ck_calendario_version CHECK (version >= 0)
);

CREATE INDEX ix_calendario_consulta ON calendario_escolar_detalle
    (institucion_id, ciclo_escolar_id, activo, fecha_inicio, fecha_fin, id);
CREATE INDEX ix_calendario_plantel ON calendario_escolar_detalle
    (plantel_id, fecha_inicio, fecha_fin) WHERE activo;
CREATE INDEX ix_calendario_nivel ON calendario_escolar_detalle
    (nivel_educativo_id, fecha_inicio, fecha_fin) WHERE activo;

INSERT INTO permiso (codigo, descripcion) VALUES
    ('CALENDARIO_ESCOLAR_LEER', 'Consultar y exportar el calendario escolar detallado'),
    ('CALENDARIO_ESCOLAR_ADMINISTRAR', 'Crear, editar y desactivar fechas del calendario escolar')
ON CONFLICT DO NOTHING;
