CREATE TABLE actualizacion_expediente_familiar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    alumno_id BIGINT NOT NULL REFERENCES alumno(id),
    tutor_id BIGINT NOT NULL REFERENCES tutor(id),
    tipo VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'ENVIADA',
    mensaje_tutor VARCHAR(2000),
    consentimiento_version VARCHAR(50) NOT NULL,
    consentimiento_texto VARCHAR(1000) NOT NULL,
    consentimiento_en TIMESTAMPTZ NOT NULL,
    archivo_id BIGINT REFERENCES archivo(id),
    tipo_documento VARCHAR(40),
    descripcion_documento VARCHAR(500),
    fecha_documento DATE,
    vigente_hasta DATE,
    tipo_sanguineo VARCHAR(20),
    alergias TEXT,
    padecimientos TEXT,
    medicamentos TEXT,
    discapacidad_necesidades TEXT,
    restricciones_fisicas TEXT,
    restricciones_alimentarias TEXT,
    servicio_medico VARCHAR(150),
    numero_afiliacion VARCHAR(100),
    medico_tratante VARCHAR(180),
    contacto_emergencia VARCHAR(180),
    telefono_emergencia VARCHAR(30),
    observaciones_medicas TEXT,
    autoriza_atencion_emergencia BOOLEAN,
    revisado_por_id BIGINT REFERENCES usuario(id),
    revisado_en TIMESTAMPTZ,
    respuesta_admin VARCHAR(2000),
    documento_aplicado_id BIGINT REFERENCES alumno_documento(id),
    ficha_medica_version_aplicada BIGINT,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_actualizacion_expediente_tipo CHECK (tipo IN ('DOCUMENTO','FICHA_MEDICA')),
    CONSTRAINT ck_actualizacion_expediente_estado CHECK (estado IN ('ENVIADA','APROBADA','RECHAZADA')),
    CONSTRAINT ck_actualizacion_expediente_version CHECK (version >= 0),
    CONSTRAINT ck_actualizacion_expediente_consentimiento CHECK (btrim(consentimiento_texto) <> ''),
    CONSTRAINT ck_actualizacion_expediente_subtipo CHECK (
        (tipo='DOCUMENTO' AND archivo_id IS NOT NULL AND tipo_documento IS NOT NULL AND tipo_sanguineo IS NULL)
        OR
        (tipo='FICHA_MEDICA' AND archivo_id IS NULL AND tipo_documento IS NULL AND tipo_sanguineo IS NOT NULL)
    ),
    CONSTRAINT ck_actualizacion_expediente_revision CHECK (
        (estado='ENVIADA' AND revisado_por_id IS NULL AND revisado_en IS NULL)
        OR
        (estado IN ('APROBADA','RECHAZADA') AND revisado_por_id IS NOT NULL AND revisado_en IS NOT NULL)
    ),
    CONSTRAINT ck_actualizacion_expediente_vigencia CHECK (
        vigente_hasta IS NULL OR fecha_documento IS NULL OR vigente_hasta >= fecha_documento
    )
);

CREATE UNIQUE INDEX ux_actualizacion_medica_pendiente
    ON actualizacion_expediente_familiar (alumno_id)
    WHERE tipo='FICHA_MEDICA' AND estado='ENVIADA';
CREATE UNIQUE INDEX ux_actualizacion_archivo
    ON actualizacion_expediente_familiar (archivo_id) WHERE archivo_id IS NOT NULL;
CREATE INDEX ix_actualizacion_expediente_bandeja
    ON actualizacion_expediente_familiar (institucion_id, estado, creado_en DESC, id DESC);
CREATE INDEX ix_actualizacion_expediente_tutor
    ON actualizacion_expediente_familiar (tutor_id, alumno_id, creado_en DESC, id DESC);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('ACTUALIZACION_EXPEDIENTE_LEER', 'Consultar propuestas familiares de documentos e información médica'),
    ('ACTUALIZACION_EXPEDIENTE_REVISAR', 'Aprobar o rechazar propuestas familiares de expedientes')
ON CONFLICT DO NOTHING;
