CREATE TABLE recuperacion_password (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id          BIGINT NOT NULL REFERENCES usuario(id),
    token_hash          VARCHAR(64) NOT NULL,
    expira_en           TIMESTAMPTZ NOT NULL,
    usado_en            TIMESTAMPTZ,
    revocado_en         TIMESTAMPTZ,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_recuperacion_password_token_hash CHECK (token_hash ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_recuperacion_password_fechas CHECK (expira_en > creado_en),
    CONSTRAINT ck_recuperacion_password_resolucion CHECK (usado_en IS NULL OR revocado_en IS NULL),
    CONSTRAINT ck_recuperacion_password_version CHECK (version >= 0),
    CONSTRAINT uq_recuperacion_password_token_hash UNIQUE (token_hash)
);

CREATE INDEX ix_recuperacion_password_usuario ON recuperacion_password (usuario_id);
CREATE UNIQUE INDEX ux_recuperacion_password_vigente
    ON recuperacion_password (usuario_id)
    WHERE usado_en IS NULL AND revocado_en IS NULL;
