CREATE TABLE proveedor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    razon_social VARCHAR(180) NOT NULL,
    nombre_comercial VARCHAR(180),
    rfc VARCHAR(13),
    contacto_nombre VARCHAR(180),
    telefono VARCHAR(30),
    correo VARCHAR(254),
    direccion VARCHAR(500),
    notas VARCHAR(2000),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_proveedor_razon CHECK (btrim(razon_social) <> ''),
    CONSTRAINT ck_proveedor_version CHECK (version >= 0)
);
CREATE UNIQUE INDEX ux_proveedor_rfc ON proveedor(institucion_id, upper(rfc)) WHERE rfc IS NOT NULL;
CREATE INDEX ix_proveedor_busqueda ON proveedor(institucion_id, activo, razon_social, id);

CREATE TABLE compra (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id BIGINT NOT NULL REFERENCES institucion(id),
    plantel_id BIGINT REFERENCES plantel(id),
    proveedor_id BIGINT NOT NULL REFERENCES proveedor(id),
    cuenta_id BIGINT NOT NULL REFERENCES cuenta_financiera(id),
    motivo_financiero_id BIGINT NOT NULL REFERENCES motivo_financiero(id),
    folio VARCHAR(40) NOT NULL,
    documento_referencia VARCHAR(150),
    fecha_operacion TIMESTAMPTZ NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'BORRADOR',
    subtotal NUMERIC(19,2) NOT NULL,
    impuesto NUMERIC(19,2) NOT NULL,
    total NUMERIC(19,2) NOT NULL,
    observaciones VARCHAR(2000),
    movimiento_egreso_id BIGINT UNIQUE REFERENCES movimiento_financiero(id),
    reversion_financiera_id BIGINT UNIQUE REFERENCES reversion_financiera(id),
    cancelada_en TIMESTAMPTZ,
    cancelada_por_id BIGINT REFERENCES usuario(id),
    motivo_cancelacion VARCHAR(2000),
    creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id BIGINT,
    actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_compra_folio UNIQUE(institucion_id, folio),
    CONSTRAINT ck_compra_estado CHECK (estado IN ('BORRADOR','CONFIRMADA','CANCELADA')),
    CONSTRAINT ck_compra_totales CHECK (subtotal >= 0 AND impuesto >= 0 AND total > 0 AND total = subtotal + impuesto),
    CONSTRAINT ck_compra_version CHECK (version >= 0),
    CONSTRAINT ck_compra_movimiento CHECK (
        (estado='BORRADOR' AND movimiento_egreso_id IS NULL AND reversion_financiera_id IS NULL)
        OR (estado='CONFIRMADA' AND movimiento_egreso_id IS NOT NULL AND reversion_financiera_id IS NULL)
        OR (estado='CANCELADA' AND movimiento_egreso_id IS NOT NULL AND reversion_financiera_id IS NOT NULL
            AND cancelada_en IS NOT NULL AND cancelada_por_id IS NOT NULL AND btrim(motivo_cancelacion) <> '')
    )
);
CREATE INDEX ix_compra_bandeja ON compra(institucion_id, estado, fecha_operacion DESC, id DESC);
CREATE INDEX ix_compra_plantel ON compra(plantel_id, fecha_operacion DESC, id DESC);
CREATE INDEX ix_compra_proveedor ON compra(proveedor_id, fecha_operacion DESC, id DESC);

CREATE TABLE compra_detalle (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id BIGINT NOT NULL REFERENCES compra(id) ON DELETE CASCADE,
    descripcion VARCHAR(300) NOT NULL,
    cantidad NUMERIC(12,3) NOT NULL,
    precio_unitario NUMERIC(19,2) NOT NULL,
    porcentaje_impuesto NUMERIC(5,2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(19,2) NOT NULL,
    impuesto NUMERIC(19,2) NOT NULL,
    total NUMERIC(19,2) NOT NULL,
    orden INTEGER NOT NULL,
    CONSTRAINT ck_compra_detalle_descripcion CHECK (btrim(descripcion) <> ''),
    CONSTRAINT ck_compra_detalle_importes CHECK (cantidad > 0 AND precio_unitario >= 0
        AND porcentaje_impuesto BETWEEN 0 AND 100 AND subtotal >= 0 AND impuesto >= 0
        AND total = subtotal + impuesto)
);
CREATE INDEX ix_compra_detalle_compra ON compra_detalle(compra_id, orden, id);

INSERT INTO permiso(codigo, descripcion) VALUES
 ('PROVEEDOR_LEER','Consultar proveedores'),
 ('PROVEEDOR_ADMINISTRAR','Crear, editar y desactivar proveedores'),
 ('COMPRA_LEER','Consultar y exportar compras'),
 ('COMPRA_ADMINISTRAR','Crear y editar compras en borrador'),
 ('COMPRA_CONFIRMAR','Confirmar compras y publicar el egreso financiero'),
 ('COMPRA_CANCELAR','Cancelar compras confirmadas mediante una reversa financiera')
ON CONFLICT DO NOTHING;
