-- Contenido editorial compartido, sin datos operativos ni progreso de pagos.
INSERT INTO permiso (codigo, descripcion) VALUES
('GUIA_PROCESOS_CONSULTAR', 'Consultar y exportar guías de procesos verificadas') ON CONFLICT DO NOTHING;

CREATE TABLE guia_proceso (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 slug VARCHAR(100) NOT NULL UNIQUE,
 titulo VARCHAR(200) NOT NULL,
 categoria VARCHAR(80) NOT NULL,
 resumen TEXT NOT NULL,
 requisitos TEXT NOT NULL,
 ejemplo TEXT NOT NULL,
 version_contenido INTEGER NOT NULL CHECK(version_contenido > 0),
 revisada_el DATE NOT NULL,
 estado VARCHAR(20) NOT NULL CHECK(estado IN ('CONFIRMADA','PENDIENTE'))
);
CREATE TABLE guia_proceso_permiso (
 guia_id BIGINT NOT NULL REFERENCES guia_proceso(id),
 permiso_id BIGINT NOT NULL REFERENCES permiso(id),
 PRIMARY KEY(guia_id, permiso_id)
);
CREATE TABLE guia_proceso_paso (
 guia_id BIGINT NOT NULL REFERENCES guia_proceso(id),
 numero INTEGER NOT NULL CHECK(numero > 0),
 titulo VARCHAR(200) NOT NULL,
 perfil VARCHAR(60) NOT NULL,
 modulo VARCHAR(120) NOT NULL,
 instrucciones TEXT NOT NULL,
 ejemplo TEXT NOT NULL,
 resultado TEXT NOT NULL,
 precaucion TEXT NOT NULL,
 ruta VARCHAR(200),
 PRIMARY KEY(guia_id, numero),
 CHECK(ruta IS NULL OR ruta LIKE '/admin/%')
);
CREATE INDEX ix_guia_categoria_estado ON guia_proceso(categoria, estado, id);

INSERT INTO guia_proceso(slug,titulo,categoria,resumen,requisitos,ejemplo,version_contenido,revisada_el,estado)
VALUES ('transferencia-dos-hijos','Una transferencia para pagar a dos hijos','Cobranza',
'Desde configurar cuotas independientes hasta validar un solo pago y revisar el comprobante. Caso confirmado por el propietario; no representa todos los escenarios de cobranza.',
'Institución, plantel, ciclo y grado activos y configurados. Dos alumnos activos con inscripciones vigentes en el mismo plantel; ambos vinculados al mismo tutor activo, con responsabilidad financiera y permiso para ver finanzas. Cuenta familiar activa y cuenta bancaria activa del mismo plantel o institucional compatible, en MXN. Usuario administrativo persistido autorizado para validar. No usar el acceso de recuperación para movimientos. Si algo ya existe, verificarlo y reutilizarlo; no duplicar expedientes.',
'Ejemplo ilustrativo: Ana Prueba debe $600.00 y Luis Prueba $400.00. Su tutor es María Prueba. Un pago de $1,000.00, un solo ingreso y dos aplicaciones independientes. Sin becas, descuentos, recargos, pagos previos ni operaciones concurrentes para reproducir exactamente los importes. Conservar el saldo inicial consultado B para verificar B + $1,000.00. Las fechas deben adaptarse al ciclo y a la fecha actual de la institución.',
1,DATE '2026-10-06','CONFIRMADA');

INSERT INTO guia_proceso_permiso(guia_id,permiso_id)
SELECT g.id,p.id FROM guia_proceso g JOIN permiso p ON p.codigo = ANY(ARRAY[
'ALUMNO_LEER','TUTOR_LEER','VINCULO_TUTOR_LEER','INSCRIPCION_LEER','CONCEPTO_COBRO_LEER',
'CUOTA_ALUMNO_LEER','CARGO_LEER','PAGO_LEER','CUENTA_FINANCIERA_LEER','PAGO_VALIDAR'])
WHERE g.slug='transferencia-dos-hijos';

INSERT INTO guia_proceso_paso(guia_id,numero,titulo,perfil,modulo,instrucciones,ejemplo,resultado,precaucion,ruta)
SELECT g.id,v.* FROM guia_proceso g CROSS JOIN (VALUES
(1,'Comprobar alumnos, inscripciones y tutor','Administración','Control escolar',
'1. En Alumnos verifica los dos expedientes activos. 2. En Inscripciones abre cada alumno y comprueba plantel, ciclo, estado y vigencia. 3. En Familiares del alumno verifica que ambos tengan al mismo tutor como responsable financiero y con permiso para ver finanzas, con vínculos activos y vigentes. 4. En Tutores → editar → Portal de familias comprueba que su cuenta está activa. Si no tiene acceso, crea la cuenta, entrega el enlace de activación y espera a que el tutor defina su contraseña.',
'Ana Prueba y Luis Prueba, mismo plantel; María Prueba responsable financiera de ambos. La inscripción y los vínculos deben estar vigentes hoy.',
'El tutor podrá seleccionar a cada hijo y consultar sus finanzas. Todavía no existe ningún pago por esta preparación.',
'No basta el parentesco para ver pagos. Si los planteles son distintos, se reportan transferencias separadas. No crear otra cuenta si el tutor ya tiene una.', '/admin/catalogos/vinculos-tutor'),
(2,'Crear o verificar el concepto de cobro','Administración','Conceptos de cobro',
'1. En Cobranza escolar → Conceptos de cobro pulsa Nuevo registro. 2. Selecciona tu institución. 3. Captura código y nombre. 4. Selecciona categoría Otro. 5. Mantén Concepto activo. Para este ejemplo deja desmarcados Permite beca, Permite descuento y Permite recargo. 6. Guarda. Si el concepto ya existe, revisa su configuración en lugar de duplicarlo.',
'Código PRUEBA-HERMANOS; nombre Cuota única de prueba para hermanos. Categoría Otro. El precio individual se define en cada cuota, no en el concepto.',
'Concepto disponible para configurar ambas cuotas; no genera deuda ni ingresos por sí mismo.',
'No cambies conceptos operativos para reproducir la prueba. Usar un concepto de ejemplo exige datos controlados autorizados.','/admin/catalogos/conceptos-cobro'),
(3,'Configurar una cuota independiente por hijo','Administración','Cuotas por alumno',
'1. En Cuotas por alumno pulsa Nuevo registro. 2. Selecciona la inscripción de Ana, el concepto e importe 600.00 MXN. 3. Elige Una sola vez, Fecha límite de pago y generación automática; estado Activa. Revisa la vigencia sugerida en Configuración adicional. 4. Guarda. 5. Repite con la inscripción de Luis e importe 400.00. Cada cuota pertenece a una inscripción; no captures una cuota familiar de 1,000.',
'Ana $600.00; Luis $400.00. Fecha límite ilustrativa 20/10/2026 y corte 06/10/2026 sólo si la vigencia ya comenzó y está dentro de inscripción y ciclo. En otra fecha adapta ambos valores, manteniendo cargos no vencidos para reportar desde el portal.',
'Dos cuotas activas. Guardarlas no ingresa dinero. Un cobro único no se repite en meses posteriores.',
'La vigencia debe quedar dentro de inscripción y ciclo. El corte debe alcanzar el inicio; no confundas fin de vigencia con fecha límite. Evita cuotas superpuestas del mismo concepto.','/admin/catalogos/cuotas-alumno'),
(4,'Revisar y generar los adeudos faltantes','Administración','Adeudos de alumnos',
'1. Abre Adeudos de alumnos → Generar automáticos. 2. Selecciona institución y plantel de ejemplo y fecha de corte. 3. Pulsa Visualizar cuotas por aplicar. 4. Revisa todas las páginas: alumno, concepto, periodo, vencimiento, importe original, beca y total por cobrar. 5. Sólo si el alcance completo es correcto pulsa Confirmar y generar adeudos faltantes. 6. Regresa al listado y consulta los dos cargos.',
'Sin becas: Ana original $600.00, beca $0.00, total $600.00; Luis original $400.00, beca $0.00, total $400.00. Total $1,000.00.',
'Dos cargos emitidos con saldo $600.00 y $400.00. La repetición del generador no duplica un cargo vigente de la misma cuota y periodo.',
'El generador incluye otras cuotas pendientes del alcance; no confirma únicamente las filas visibles. La vista no crea registros. Si una beca cambia, vuelve a consultar. Becas y recargos son variantes separadas, no parte de este resultado exacto.','/admin/cargos/generar'),
(5,'Anotar el saldo bancario de referencia','Administración','Cuentas financieras',
'1. En Cuentas financieras identifica la cuenta bancaria donde se recibió la transferencia. 2. Consulta Saldo actual en la tabla o detalle. 3. Anota ese saldo como B antes de validar el pago. 4. Confirma que cuenta y moneda corresponden al plantel de los cargos. No modifiques el saldo inicial para probar.',
'Si B = $2,000.00, después de validar debe quedar $3,000.00, siempre que no haya otros movimientos durante la comprobación.',
'Referencia de saldo para comparar el ingreso real del pago.',
'Saldo inicial y saldo actual son distintos. Otros ingresos, egresos o traspasos cambian la comparación; comprueba el movimiento vinculado al pago.','/admin/catalogos/cuentas-financieras'),
(6,'Reportar una sola transferencia desde la familia','Tutor','Portal familiar → Tus pagos',
'1. El tutor entra desde /familias con su propia cuenta. Para pruebas del administrador usa una sesión privada separada; no sustituyas la sesión administrativa. 2. En Tus pagos pulsa Reportar transferencia. 3. Selecciona el cargo de Ana; pulsa Agregar cargo y elige el de Luis. 4. Comprueba el total calculado. 5. Selecciona Cuenta destino registrada. 6. Captura fecha y hora del comprobante, referencia bancaria, pagador si es distinto y observaciones si corresponde. 7. Adjunta el comprobante. 8. Revisa el resumen final y pulsa Enviar transferencia a revisión.',
'Ana $600.00 + Luis $400.00 = $1,000.00. Referencia ilustrativa TEST-HERMANOS-1000 sólo en una prueba autorizada; en operación usa la referencia y comprobante auténticos. Fecha y hora reales, no futuras. PDF/JPG/PNG hasta 5 archivos de 10 MB.',
'Un pago En revisión con dos distribuciones solicitadas. La cuenta y los saldos de los cargos todavía no cambian. Los montos completos se calculan, no se capturan libremente en el portal.',
'La ayuda muestra diez cargos al enfocar y busca desde tres caracteres. Cargos vencidos, cancelados o liquidados no aparecen en esa captura. No reportes dos veces la misma transferencia. Adjuntar un comprobante no valida el pago.',NULL),
(7,'Validar el pago y publicar un solo ingreso','Administración','Pagos recibidos',
'1. En Pagos recibidos busca el pago en revisión y pulsa Ver. 2. En Comprobantes abre el archivo en otra pestaña y comprueba transferencia, fecha, cuenta y referencia. 3. En Distribución verifica los dos alumnos y sus importes. 4. En Gestión revisa la cuenta destino precargada. Conserva la cuenta declarada si es correcta. 5. Sólo después de comprobar la recepción real pulsa Validar y publicar. 6. Comprueba el estado Validado y su movimiento financiero.',
'Pago total $1,000.00; distribución Ana $600.00 y Luis $400.00; dinero pendiente de asignar $0.00. Un único ingreso de $1,000.00 a la cuenta elegida.',
'Pago validado, dos aplicaciones independientes y un solo ingreso. Cuenta B + $1,000.00; cargos con saldo $0.00.',
'Cambiar cuenta destino es excepcional y requiere motivo si cambia realmente. El acceso de recuperación no puede validar. Si otro pago consumió saldo mientras estaba en revisión, verifica la distribución efectiva: no supongas que coincide con la solicitada.','/admin/catalogos/pagos'),
(8,'Comprobar el resultado para cada hijo','Administración y tutor','Distribución, cuentas y portal familiar',
'1. Administración revisa Distribución del pago: $600 para Ana y $400 para Luis. 2. En Cuentas financieras verifica el incremento y el movimiento vinculado al pago. 3. En el portal familiar selecciona Ana → Tus pagos: su cargo ya no aparece en Lo que falta por pagar y su historial refleja $600. 4. Selecciona Luis y comprueba $400 y ausencia de deuda de ese cargo. 5. Pulsa Ver comprobante PDF; se abre en una pestaña nueva, sin descarga automática. El visor permite descargar si se desea.',
'Cuenta: incremento $1,000.00. Ana: pagado $600.00, pendiente de ese cargo $0.00. Luis: pagado $400.00, pendiente de ese cargo $0.00. Un comprobante del pago compartido con ambas aplicaciones.',
'Caso confirmado: una transferencia, un ingreso, deuda individual liquidada, historial separado por hijo y comprobante disponible.',
'El resumen puede incluir otros cargos históricos. Al corriente sólo aparece si no existe otro saldo pendiente para ese hijo. Los filtros de mes/año afectan el historial, no la deuda. No borres registros para corregir errores.', '/admin/catalogos/pagos')
) AS v(numero,titulo,perfil,modulo,instrucciones,ejemplo,resultado,precaucion,ruta)
WHERE g.slug='transferencia-dos-hijos';
