CREATE TABLE alumno (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    matricula           VARCHAR(50) NOT NULL,
    nombres             VARCHAR(150) NOT NULL,
    primer_apellido     VARCHAR(100) NOT NULL,
    segundo_apellido    VARCHAR(100),
    curp                VARCHAR(18),
    fecha_nacimiento    DATE NOT NULL,
    sexo                VARCHAR(30),
    lugar_nacimiento    VARCHAR(150),
    nacionalidad        VARCHAR(80),
    telefono            VARCHAR(30),
    email               VARCHAR(254),
    calle               VARCHAR(150),
    numero_exterior     VARCHAR(30),
    numero_interior     VARCHAR(30),
    colonia             VARCHAR(120),
    ciudad              VARCHAR(100),
    estado              VARCHAR(100),
    codigo_postal       VARCHAR(15),
    pais                VARCHAR(2),
    fecha_ingreso       DATE NOT NULL,
    observaciones       TEXT,
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_alumno_matricula_no_vacia CHECK (btrim(matricula) <> ''),
    CONSTRAINT ck_alumno_nombres_no_vacios CHECK (btrim(nombres) <> ''),
    CONSTRAINT ck_alumno_primer_apellido_no_vacio CHECK (btrim(primer_apellido) <> ''),
    CONSTRAINT ck_alumno_curp CHECK (curp IS NULL OR curp ~ '^[A-Z0-9]{18}$'),
    CONSTRAINT ck_alumno_fechas CHECK (fecha_ingreso >= fecha_nacimiento),
    CONSTRAINT ck_alumno_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_alumno_institucion_matricula
    ON alumno (institucion_id, upper(btrim(matricula)));
CREATE UNIQUE INDEX ux_alumno_institucion_curp
    ON alumno (institucion_id, upper(btrim(curp)))
    WHERE curp IS NOT NULL;
CREATE INDEX ix_alumno_institucion_activo
    ON alumno (institucion_id, activo);
CREATE INDEX ix_alumno_apellidos
    ON alumno (institucion_id, primer_apellido, segundo_apellido, nombres);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('ALUMNO_LEER', 'Consultar alumnos'),
    ('ALUMNO_ADMINISTRAR', 'Crear y modificar alumnos');
