-- Sólo contenido editorial del escenario confirmado; no mueve fondos ni concede roles.
INSERT INTO guia_proceso(slug,titulo,categoria,resumen,requisitos,ejemplo,version_contenido,revisada_el,estado) VALUES
('devolucion-parcial-descuento-100','Devolver $100 y ajustar la deuda con un descuento','Cobranza',
'Devolución parcial de $100 de un pago de $400 y descuento autorizado de $100: total ajustado y aplicado $300, saldo cero, sin otra salida de dinero.',
'Alumno con inscripción activa y tutor con acceso financiero vigente; concepto de prueba que permita descuento, sin becas ni recargos. Administrador persistido autorizado para conceptos, cuotas, cargos, pagos, devoluciones, ajustes y cuentas. Usar un cargo nuevo distinto del ya liquidado mediante otro pago; adaptar fechas al ciclo y al día real.',
'Caso confirmado por el propietario: pagar $400, devolver $100 y descontar $100 deja original $400, descuento $100, total ajustado $300, aplicado $300 y saldo $0. S es el saldo de cuenta tras el pago: devolución lo reduce a S menos $100 y descuento lo conserva. No volver a pagar el mismo saldo descontado.',
1,DATE '2026-10-07','CONFIRMADA');
INSERT INTO guia_proceso_permiso(guia_id,permiso_id)
SELECT g.id,p.id FROM guia_proceso g JOIN permiso p ON p.codigo=ANY(ARRAY['CONCEPTO_COBRO_ADMINISTRAR','CUOTA_ALUMNO_ADMINISTRAR','CARGO_ADMINISTRAR','AJUSTE_CARGO_ADMINISTRAR','PAGO_LEER','PAGO_VALIDAR','PAGO_DEVOLVER','CUENTA_FINANCIERA_LEER'])
WHERE g.slug='devolucion-parcial-descuento-100';
INSERT INTO guia_proceso_paso(guia_id,numero,titulo,perfil,modulo,instrucciones,ejemplo,resultado,precaucion,ruta)
SELECT g.id,v.* FROM guia_proceso g CROSS JOIN (VALUES
(1,$texto$Preparar un concepto que permita descuentos$texto$,$texto$Administración$texto$,$texto$Conceptos de cobro$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Conceptos de cobro. Busca DEV-DESC-TEST y pulsa Aplicar filtros. 2. Si no existe, pulsa Nuevo registro; elige la institución del alumno, Código DEV-DESC-TEST, Nombre Prueba devolución y descuento y Categoría Otro. 3. Habilita Activo y Permite descuento; deja sin beca ni recargo para aislar este caso. Pulsa Crear concepto. Si ya existe, pulsa Editar, revisa esas reglas y Guarda cambios sin alterar un concepto operativo. 4. Anota el concepto y comprueba su estado antes de configurar la cuota.$texto$,$texto$Concepto DEV-DESC-TEST activo, permite descuento.$texto$,$texto$El concepto admite el ajuste manual del ejemplo.$texto$,$texto$Usar otro cargo distinto del caso ya liquidado por nuevo pago; no repetir operaciones al consultar la guía.$texto$,$texto$/admin/catalogos/conceptos-cobro$texto$),
(2,$texto$Configurar una cuota nueva por $400$texto$,$texto$Administración$texto$,$texto$Cuotas por alumno$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Cuotas por alumno → Nuevo registro. 2. Selecciona institución, plantel, inscripción activa del alumno de prueba y concepto DEV-DESC-TEST mediante las ayudas; enfoca para las primeras opciones o escribe tres caracteres y elige el registro. 3. Elige Una sola vez, Importe 400.00 y moneda de la institución. Usa Fecha límite de pago vigente dentro del rango permitido por inscripción/ciclo; por ejemplo 20/10/2026 sólo si pertenece a ese rango. Revisa la vigencia en Configuración adicional: su inicio no debe ser posterior al corte de generación. 4. Habilita la cuota e Incluir en generación automática de cargos. En Así quedará la cuota revisa alumno, importe y vencimiento; pulsa Crear cuota. 5. Para comprobar captura monetaria, escribe 400, desplázate con la rueda sin que cambie el valor y sal del campo: debe verse $400.00. Al enfocarlo se muestra decimal. Comprueba después del guardado que conserva $400.00.$texto$,$texto$Cuota única nueva $400.00, sin becas/recargos ni solapamientos.$texto$,$texto$Cuota configurada; todavía no se recibió dinero ni se emitió el cargo.$texto$,$texto$Si ya existe la cuota de esta prueba, consultar su historial en vez de crear una duplicada. Nunca forzar fechas fuera del ciclo.$texto$,$texto$/admin/catalogos/cuotas-alumno$texto$),
(3,$texto$Emitir solamente el adeudo de esta prueba$texto$,$texto$Administración$texto$,$texto$Adeudos de alumnos → Generar automáticos$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Adeudos de alumnos → Generar automáticos. 2. Selecciona institución, plantel y fecha de corte actual válida; pulsa Visualizar cuotas por aplicar. 3. En Cuotas que generarán adeudos pulsa Desmarcar todos y marca únicamente la cuota DEV-DESC-TEST del alumno por $400.00. Verifica original $400.00, beca $0.00 y total por cobrar $400.00. 4. Comprueba resumen de selección: un registro por $400.00; pulsa Confirmar y generar adeudos seleccionados. 5. Regresa a Adeudos de alumnos, busca matrícula, pulsa Aplicar filtros y Ver del nuevo registro. En Resumen comprueba original/total $400.00, pagado $0.00 y saldo $400.00; anota número de cargo y matrícula.$texto$,$texto$Un cargo por $400.00 para DEV-DESC-TEST.$texto$,$texto$Adeudo emitido, separado de los otros casos.$texto$,$texto$Cuotas no incluidas es diagnóstico, no lista por generar. No seleccionar pruebas anteriores ni cancelar para intentar regenerar.$texto$,$texto$/admin/catalogos/cargos$texto$),
(4,$texto$Reportar la transferencia original de $400$texto$,$texto$Tutor$texto$,$texto$Portal familiar → Tus pagos → Reportar transferencia$texto$,$texto$1. Abre una ventana privada separada de administración y entra a /familias después de la dirección del sistema con el tutor del alumno. Desde el inicio selecciona al hijo y pulsa Tus pagos. 2. Pulsa Reportar transferencia; enfoca Cargo pendiente del alumno y selecciona el cargo anotado de DEV-DESC-TEST. 3. Verifica un único cargo y Total a transferir $400.00 protegido. Selecciona la cuenta bancaria del plantel. Captura fecha/hora válidas, Referencia TEST-DEV-DESC-400 y adjunta el comprobante de prueba legible. 4. En Revisa y envía comprueba alumno, cargo, monto, cuenta y archivo; pulsa Enviar transferencia a revisión. 5. En Tus pagos y comprobantes anota el nuevo folio En revisión. El saldo todavía debe ser $400.00; reportar no publica un ingreso.$texto$,$texto$Reporte familiar $400.00, TEST-DEV-DESC-400.$texto$,$texto$Pago pendiente de validación, sin cambiar saldo de cuenta.$texto$,$texto$Referencias TEST sólo ilustrativas; en operación usar fecha, referencia y comprobante auténticos. No hacer una segunda transferencia por leer esta guía.$texto$,NULL),
(5,$texto$Validar el pago y anotar el saldo de cuenta$texto$,$texto$Administración$texto$,$texto$Pagos recibidos y Cuentas financieras$texto$,$texto$1. Desde el menú lateral entra a Administración → Finanzas → Pagos recibidos; busca TEST-DEV-DESC-400 o folio anotado, pulsa Aplicar filtros → Ver. 2. En Comprobantes abre el archivo en otra pestaña y verifica recepción real, monto, fecha y referencia. En Distribución comprueba el cargo correcto por $400.00. 3. En Gestión conserva la cuenta destino precargada y pulsa Validar y publicar. Revisa el modal por $400.00 y cuenta correcta; pulsa Confirmar operación una sola vez. 4. Comprueba Validado, aplicado $400.00 y saldo del cargo $0.00. 5. Desde el menú lateral entra a Administración → Finanzas → Cuentas financieras; busca esa cuenta → Aplicar filtros. Anota Saldo actual como S: ya incluye el ingreso original. No cambies Saldo inicial.$texto$,$texto$Si S=$2,400.00 después de validar, ése es el punto de comparación previo a la devolución.$texto$,$texto$Ingreso original registrado y cargo inicialmente liquidado.$texto$,$texto$Comprobar ingreso bancario antes de validar; no añadir otro movimiento manual. El sistema registra el movimiento, no ejecuta la transferencia bancaria.$texto$,$texto$/admin/catalogos/pagos$texto$),
(6,$texto$Devolver $100 del pago original$texto$,$texto$Administración$texto$,$texto$Pagos recibidos → Ver → Devoluciones$texto$,$texto$1. Desde el menú lateral entra a Administración → Finanzas → Pagos recibidos; busca el folio original de $400.00 → Aplicar filtros → Ver → Devoluciones. 2. En Ejecutar devolución conserva Cuenta de origen protegida y Beneficiario; no actives Devolver desde otra cuenta para este caso. Captura fecha/hora actual válida, no futura ni anterior al pago. 3. Elige Devolución parcial y Dinero a devolver 100.00. Captura Referencia TEST-DEV-DESC-100 y Motivo El cobro autorizado será de $300; se devuelven $100. 4. En Abonos de los que se devolverá dinero selecciona sólo el abono original de $400.00 del cargo anotado. En Así quedaría la devolución verifica devolver $100.00, permanecer aplicado $300.00 y deuda recuperada $100.00. 5. Pulsa Ejecutar devolución y publicar egreso; revisa monto, cuenta y efecto en el modal y pulsa Confirmar operación. 6. En Devoluciones comprueba historial devuelto $100.00; en Distribución comprueba aplicado $300.00 y saldo por pagar $100.00.$texto$,$texto$Cargo original $400.00, aplicado $300.00, deuda $100.00; cuenta S menos $100.00.$texto$,$texto$Un egreso de $100.00 recupera parte de la deuda; el pago sigue Validado.$texto$,$texto$Devolver registra salida real: no es cancelar ni descontar. En operación registrar el dinero efectivamente devuelto; no crear otro egreso manual.$texto$,$texto$/admin/catalogos/pagos$texto$),
(7,$texto$Comprobar el saldo recuperado antes del descuento$texto$,$texto$Administración$texto$,$texto$Adeudos de alumnos y Cuentas financieras$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Adeudos de alumnos; busca matrícula → Aplicar filtros → Ver del cargo anotado → Resumen. 2. Comprueba original/total $400.00, pagado acumulado $300.00 y saldo $100.00. Si no coincide, detente antes del ajuste. 3. Desde el menú lateral entra a Administración → Finanzas → Cuentas financieras; busca la cuenta → Aplicar filtros. Comprueba S menos $100.00 y anota ese saldo como D. 4. Conserva el número de cargo para ajustar sólo esa deuda, no otro registro del alumno.$texto$,$texto$Si S=$2,400.00, D=$2,300.00; deuda recuperada $100.00.$texto$,$texto$Saldo antes del ajuste identificado.$texto$,$texto$Sin otros movimientos simultáneos. Si los hay, comparar los movimientos vinculados; no atribuir toda variación al ejemplo.$texto$,$texto$/admin/catalogos/cargos$texto$),
(8,$texto$Aplicar el descuento autorizado de $100$texto$,$texto$Administración$texto$,$texto$Adeudos de alumnos → Ver → Ajustar saldo$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Adeudos de alumnos; busca matrícula → Aplicar filtros → Ver del mismo cargo → pestaña Ajustar saldo. 2. En Ajustar saldo del cargo selecciona Tipo Descuento y verifica Efecto Disminucion; captura Monto 100.00 y Fecha efectiva actual válida. 3. Captura Motivo Descuento autorizado: el cobro correcto es $300. Devolución de $100 previamente registrada. 4. En Así quedaría el cargo verifica total actual $400.00, ajuste de disminución $100.00, nuevo total ajustado $300.00, pagado acumulado $300.00 y Saldo después del ajuste $0.00. 5. Pulsa Aplicar ajuste al saldo. En Confirmar ajuste al saldo revisa alumno, número de cargo, descuento, monto y saldo final $0.00. Volver a revisar no guarda; si todo coincide pulsa Confirmar operación. 6. El sistema abre Historial: comprueba ajuste registrado y motivo. No apliques nuevamente el descuento.$texto$,$texto$Descuento $100.00: total ajustado $300.00, pagado $300.00, saldo $0.00.$texto$,$texto$Descuento registrado sin entrada ni salida de dinero adicional.$texto$,$texto$Requiere concepto que permita descuento. Primero devolver y después descontar: no reducir por debajo de lo ya pagado. No volver a pagar esos mismos $100.00.$texto$,$texto$/admin/catalogos/cargos$texto$),
(9,$texto$Verificar el cierre del caso en ambos perfiles$texto$,$texto$Administración y tutor$texto$,$texto$Adeudos, pagos, cuentas y portal familiar$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Adeudos de alumnos; busca matrícula → Aplicar filtros → Ver del cargo → Resumen. Verifica original $400.00, descuento $100.00, total ajustado $300.00, pagado acumulado $300.00 y saldo $0.00. En Historial conserva ajuste y motivo. 2. Desde el menú lateral entra a Administración → Finanzas → Cuentas financieras; busca cuenta → Aplicar filtros. Saldo actual debe seguir en D, igual que después de devolver: el descuento no mueve fondos. 3. Desde el menú lateral entra a Administración → Finanzas → Pagos recibidos; busca folio original → Aplicar filtros → Ver → Devoluciones. Conserva historial devuelto $100.00 y pago Validado original de $400.00. En Distribución comprueba aplicado neto $300.00. 4. En la ventana familiar, desde el inicio selecciona el hijo → Tus pagos. En Lo que falta por pagar ya no deben aparecer esos $100.00. Consulta el folio en Tus pagos y comprobantes; limpia filtros de mes/año, pulsa Buscar pagos y pagina si hace falta. 5. Para recordar ambos caminos entra a Administración → Seguridad y soporte → Guía de procesos: compara esta guía con Devolver $100 y pagar nuevamente el saldo. Son alternativas sobre cargos distintos.$texto$,$texto$Original $400.00 - descuento $100.00 = ajustado $300.00; pago $400.00 - devolución $100.00 = aplicado $300.00; saldo $0.00. S=$2,400.00 → devolución=$2,300.00 → descuento=$2,300.00.$texto$,$texto$Caso confirmado por el propietario: saldo cero, descuento en historial, cuenta sin variación adicional y sin deuda familiar.$texto$,$texto$No repetir descuento ni devolución; no borrar historial. Este caso no certifica devolución total, otra cuenta, cancelación ni reversa de descuento.$texto$,$texto$/admin/catalogos/cargos$texto$)
) AS v(numero,titulo,perfil,modulo,instrucciones,ejemplo,resultado,precaucion,ruta)
WHERE g.slug='devolucion-parcial-descuento-100';

-- Enlazar la alternativa ya confirmada sin reescribir migraciones anteriores.
UPDATE guia_proceso_paso
SET precaucion='Conservar pago original, devolución y pago nuevo; no borrar ni compensar con descuento. La alternativa confirmada Devolver $100 y ajustar la deuda con un descuento se realiza sobre otro cargo: no volver a pagar y descontar los mismos $100.'
WHERE guia_id=(SELECT id FROM guia_proceso WHERE slug='devolucion-parcial-nuevo-pago-100') AND numero=8;
UPDATE guia_proceso SET version_contenido=version_contenido+1,revisada_el=DATE '2026-10-07'
WHERE slug='devolucion-parcial-nuevo-pago-100';
