CREATE TABLE tutor (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id      BIGINT NOT NULL REFERENCES institucion(id),
    usuario_id          BIGINT REFERENCES usuario(id),
    nombres             VARCHAR(150) NOT NULL,
    primer_apellido     VARCHAR(100) NOT NULL,
    segundo_apellido    VARCHAR(100),
    telefono_principal  VARCHAR(30) NOT NULL,
    telefono_secundario VARCHAR(30),
    email               VARCHAR(254),
    fecha_nacimiento    DATE,
    calle               VARCHAR(150),
    numero_exterior     VARCHAR(30),
    numero_interior     VARCHAR(30),
    colonia             VARCHAR(120),
    ciudad              VARCHAR(100),
    estado              VARCHAR(100),
    codigo_postal       VARCHAR(15),
    pais                VARCHAR(2),
    ocupacion           VARCHAR(120),
    lugar_trabajo       VARCHAR(180),
    telefono_trabajo    VARCHAR(30),
    activo              BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id       BIGINT,
    actualizado_en      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id  BIGINT,
    version             BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_tutor_nombres_no_vacios CHECK (btrim(nombres) <> ''),
    CONSTRAINT ck_tutor_primer_apellido_no_vacio CHECK (btrim(primer_apellido) <> ''),
    CONSTRAINT ck_tutor_telefono_principal_no_vacio CHECK (btrim(telefono_principal) <> ''),
    CONSTRAINT ck_tutor_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_tutor_usuario ON tutor (usuario_id) WHERE usuario_id IS NOT NULL;
CREATE INDEX ix_tutor_institucion_activo ON tutor (institucion_id, activo);
CREATE INDEX ix_tutor_apellidos
    ON tutor (institucion_id, primer_apellido, segundo_apellido, nombres);
CREATE INDEX ix_tutor_telefono ON tutor (institucion_id, telefono_principal);

INSERT INTO permiso (codigo, descripcion) VALUES
    ('TUTOR_LEER', 'Consultar tutores'),
    ('TUTOR_ADMINISTRAR', 'Crear y modificar tutores');
