CREATE TABLE alumno_tutor (
    id                              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id                       BIGINT NOT NULL REFERENCES alumno(id),
    tutor_id                        BIGINT NOT NULL REFERENCES tutor(id),
    parentesco                      VARCHAR(20) NOT NULL,
    parentesco_otro                 VARCHAR(100),
    es_contacto_principal           BOOLEAN NOT NULL DEFAULT FALSE,
    es_responsable_financiero       BOOLEAN NOT NULL DEFAULT FALSE,
    puede_autorizar                 BOOLEAN NOT NULL DEFAULT FALSE,
    puede_recoger                   BOOLEAN NOT NULL DEFAULT FALSE,
    puede_ver_finanzas              BOOLEAN NOT NULL DEFAULT FALSE,
    puede_recibir_notificaciones    BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_inicio                    DATE NOT NULL,
    fecha_fin                       DATE,
    observaciones                   VARCHAR(4000),
    activo                          BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en                       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id                   BIGINT,
    actualizado_en                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id              BIGINT,
    version                         BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_alumno_tutor_parentesco
        CHECK (parentesco IN ('MADRE', 'PADRE', 'TUTOR_LEGAL', 'OTRO')),
    CONSTRAINT ck_alumno_tutor_parentesco_otro CHECK (
        (parentesco = 'OTRO' AND parentesco_otro IS NOT NULL AND btrim(parentesco_otro) <> '')
        OR (parentesco <> 'OTRO' AND parentesco_otro IS NULL)
    ),
    CONSTRAINT ck_alumno_tutor_fechas
        CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_alumno_tutor_version CHECK (version >= 0)
);

CREATE INDEX ix_alumno_tutor_alumno ON alumno_tutor (alumno_id, activo);
CREATE INDEX ix_alumno_tutor_tutor ON alumno_tutor (tutor_id, activo);
CREATE INDEX ix_alumno_tutor_vigencia ON alumno_tutor (fecha_inicio, fecha_fin);
CREATE UNIQUE INDEX ux_alumno_tutor_abierto
    ON alumno_tutor (alumno_id, tutor_id)
    WHERE activo AND fecha_fin IS NULL;
CREATE UNIQUE INDEX ux_alumno_tutor_contacto_principal_abierto
    ON alumno_tutor (alumno_id)
    WHERE activo AND es_contacto_principal AND fecha_fin IS NULL;

INSERT INTO permiso (codigo, descripcion) VALUES
    ('VINCULO_TUTOR_LEER', 'Consultar vínculos entre alumnos y tutores'),
    ('VINCULO_TUTOR_ADMINISTRAR', 'Crear y modificar vínculos entre alumnos y tutores');
