-- Confirmación humana de cancelación y reaparición familiar; sólo contenido editorial.
INSERT INTO guia_proceso(slug,titulo,categoria,resumen,requisitos,ejemplo,version_contenido,revisada_el,estado)
VALUES ('cancelar-condonacion-total-500',$texto$Cancelar una condonación total: recuperar el adeudo de $500$texto$,'Cobranza',$texto$Anular un convenio de condonación total con motivo y confirmación para reactivar el adeudo original, conservando historial y sin registrar un pago.$texto$,$texto$Convenio de prueba de condonación total previamente creado sobre un adeudo de $500.00 sin abonos. Tutor con acceso familiar y administrador persistido autorizado para convenios, adeudos y consulta de cuentas. Usar el convenio de prueba, no una condonación real que deba mantenerse. Si ya está cancelado, consultar su resultado: no repetir la operación ni duplicar registros.$texto$,$texto$Antes: convenio Condonado totalmente, deuda exigible $0.00 y original conservado. Después: convenio Cancelado, original vuelve a ser exigible por $500.00 y reaparece para pagar en el portal familiar. No hay cargos nuevos ni pago; la reversión no mueve dinero.$texto$,1,DATE '2026-10-08','CONFIRMADA');
INSERT INTO guia_proceso_permiso(guia_id,permiso_id)
SELECT g.id,p.id FROM guia_proceso g JOIN permiso p ON p.codigo=ANY(ARRAY['CONVENIO_PAGO_ADMINISTRAR','CARGO_ADMINISTRAR','CUENTA_FINANCIERA_LEER']) WHERE g.slug='cancelar-condonacion-total-500';
INSERT INTO guia_proceso_paso(guia_id,numero,titulo,perfil,modulo,instrucciones,ejemplo,resultado,precaucion,ruta)
SELECT g.id,v.numero,v.titulo,v.perfil,v.modulo,v.instrucciones,v.ejemplo,v.resultado,v.precaucion,v.ruta FROM guia_proceso g JOIN (VALUES
('cancelar-condonacion-total-500',1,$texto$Identificar el convenio de condonación de prueba$texto$,$texto$Administración$texto$,$texto$Convenios de pago$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Convenios de pago. Busca el folio anotado al condonar el adeudo de $500.00; filtra Condonado totalmente y aplica filtros. 2. Pulsa Ver → Resumen. Confirma tutor, saldo original $500.00, monto por pagar $0.00, condonado $500.00 y estado Condonado totalmente. 3. En el detalle revisa Adeudos; anota número y alumno del original, sin nuevos cargos. Confirma que es el convenio de prueba y no el acuerdo anterior de $800.00 liquidado. 4. Si no tienes una condonación de prueba, entra a Administración → Seguridad y soporte → Guía de procesos, busca Condonar totalmente un adeudo mediante convenio: $500 a $0 y sigue esa preparación completa; después regresa a este caso. Si ya cancelaste el convenio, consulta las verificaciones finales sin volver a ejecutar.$texto$,$texto$Un convenio de condonación total sobre saldo pendiente $500.00.$texto$,$texto$Acuerdo y original identificados sin duplicar.$texto$,$texto$No cancelar una condonación real que deba conservarse; la operación vuelve a exigir la deuda al tutor.$texto$,$texto$/admin/convenios-pago$texto$),
('cancelar-condonacion-total-500',2,$texto$Anotar saldo bancario antes de revertir$texto$,$texto$Administración$texto$,$texto$Cuentas financieras$texto$,$texto$1. Desde el menú lateral entra a Administración → Finanzas → Cuentas financieras. 2. Busca la cuenta bancaria de prueba y pulsa Aplicar filtros. 3. Anota Saldo actual como B, por ejemplo $2,000.00; usa siempre el valor real de tu cuenta. 4. No edites saldo inicial ni registres entradas o salidas: esta cancelación reactiva un adeudo, no devuelve ni recibe dinero.$texto$,$texto$Banco B antes de cancelar.$texto$,$texto$Referencia para verificar ausencia de efecto financiero.$texto$,$texto$Si hay movimientos de otros usuarios durante la prueba, identifícalos por separado; no atribuirlos al convenio.$texto$,$texto$/admin/catalogos/cuentas-financieras$texto$),
('cancelar-condonacion-total-500',3,$texto$Comprobar que el original aún está condonado$texto$,$texto$Administración y tutor$texto$,$texto$Adeudos de alumnos y portal familiar$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Adeudos de alumnos; busca matrícula, elige Situación del adeudo Incluido en convenio → Aplicar filtros → Ver del original anotado. Comprueba abonos $0.00 y saldo exigible $0.00; el cargo sigue en historial. 2. Abre una ventana privada separada, entra a /familias e inicia sesión con el tutor responsable; selecciona el hijo → Tus pagos. 3. Confirma que el original de $500.00 todavía no aparece como deuda pendiente. Identifica por número/concepto; puede haber otros adeudos del alumno. 4. Regresa a la ventana administrativa. Sólo consulta: no generes otra cuota, no apliques descuento ni reportes una transferencia.$texto$,$texto$Original incluido en convenio, sin deuda exigible antes de cancelar.$texto$,$texto$Estado inicial verificado en ambos portales.$texto$,$texto$Si el original ya es exigible y el convenio está Cancelado, la reversión ya ocurrió; omite la captura y revisa el historial.$texto$,$texto$/admin/catalogos/cargos$texto$),
('cancelar-condonacion-total-500',4,$texto$Cancelar la condonación con motivo y modal$texto$,$texto$Administración$texto$,$texto$Convenios de pago → Gestión$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Convenios de pago; busca el folio → aplica filtros → Ver → Gestión → Cancelar convenio. 2. Captura Motivo obligatorio: Prueba controlada: se anula la condonación total y se reactiva el adeudo original de $500.00. Pulsa Cancelar y reactivar adeudos. 3. En Confirmar cancelación del convenio revisa folio, tutor, original $500.00 a reactivar, acuerdo $0.00, condonación $500.00, motivo y mensaje de ningún movimiento financiero. Debe indicar que no existen cargos nuevos. Puedes pulsar Cancelar para cerrar sin ejecutar y conservar el motivo. 4. Pulsa nuevamente Cancelar y reactivar adeudos si cerraste el modal; revisa y pulsa Confirmar cancelación del convenio una sola vez. Espera estado Cancelado y motivo conservado.$texto$,$texto$Se anula el perdón del saldo; el original vuelve a ser exigible.$texto$,$texto$Cancelación formal, con motivo e historial.$texto$,$texto$Cancelar en el modal sólo cierra. Si el servidor avisa que abonos o ajustes del original cambiaron, revisar historial antes de restaurar; no eludir la validación.$texto$,$texto$/admin/convenios-pago$texto$),
('cancelar-condonacion-total-500',5,$texto$Verificar convenio cancelado y deuda restaurada$texto$,$texto$Administración$texto$,$texto$Convenios de pago y Adeudos de alumnos$texto$,$texto$1. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Convenios de pago; busca folio, filtra Cancelado → aplica filtros → Ver → Gestión. Comprueba Convenio cancelado y el motivo capturado. 2. En el detalle revisa Resumen e historial: la autorización original y los importes $500.00/$0.00/$500.00 se conservan como datos del acuerdo anulado, no como condonación activa. No hay nuevos cargos de cero. 3. Desde el menú lateral entra a Operación escolar → Cobranza escolar → Adeudos de alumnos; busca matrícula, selecciona Con saldo pendiente → Aplicar filtros → Ver → Resumen del original. Verifica abonos $0.00 y saldo exigible $500.00. 4. Comprueba que es el mismo número de cargo, no otro adeudo creado. Si su fecha límite ya pasó aparecerá Vencido; lo importante es que el saldo original vuelva a ser exigible, no que siempre diga Pendiente.$texto$,$texto$Mismo adeudo original $500.00 exigible; convenio Cancelado.$texto$,$texto$Trazabilidad conservada y deuda restaurada.$texto$,$texto$Cancelar el convenio no cancela el adeudo ni borra su historial; no usar Cancelar cargo al alumno para esta reversión.$texto$,$texto$/admin/catalogos/cargos$texto$),
('cancelar-condonacion-total-500',6,$texto$Comprobar reaparición para pagar en el portal familiar$texto$,$texto$Tutor$texto$,$texto$Portal familiar → Tus pagos$texto$,$texto$1. En la ventana privada separada entra a /familias, inicia sesión con el tutor si es necesario y selecciona el hijo de la prueba. 2. Abre Tus pagos y recarga la pantalla para consultar la situación actual. 3. Identifica el original por concepto/número: debe volver a aparecer con $500.00 pendientes, sin otro cargo nuevo por la cancelación. No confundas otros adeudos del hijo con el ejemplo. 4. Para cerrar esta prueba sólo verifica la deuda; no envíes transferencia ni registres pago. El propietario confirmó el 08/10/2026 que canceló el convenio y el adeudo reapareció para pagar en el portal familiar.$texto$,$texto$La deuda condonada vuelve al portal tras cancelar el convenio.$texto$,$texto$Cancelación y reaparición familiar confirmadas por el propietario.$texto$,$texto$Si el adeudo está vencido, su reporte de transferencia sigue sujeto a la autorización administrativa de cargos vencidos; esta cancelación no habilita por sí misma esa excepción.$texto$,NULL),
('cancelar-condonacion-total-500',7,$texto$Verificar cuenta y exportar historial de cancelación$texto$,$texto$Administración$texto$,$texto$Cuentas financieras y Convenios de pago$texto$,$texto$1. Desde el menú lateral entra a Administración → Finanzas → Cuentas financieras; busca la cuenta → Aplicar filtros y compara Saldo actual con B. La cancelación no debe sumar ni restar dinero. 2. Entra desde el menú lateral a Operación escolar → Cobranza escolar → Convenios de pago; filtra Cancelado y busca folio → aplica filtros → Exportar Excel. 3. En Excel identifica el mismo folio con estado Cancelado e importes históricos original $500.00, acordado $0.00 y condonado $500.00; el saldo actual del adeudo se consulta en Adeudos de alumnos, no restando esos importes históricos. 4. Conserva motivo, autorización y registros originales. El caso comprobó la cancelación y el regreso de la deuda; si después quieres pagarla, sigue otro proceso de pago normal y registra su resultado por separado.$texto$,$texto$Banco B; convenio cancelado conservado en historial y Excel.$texto$,$texto$Reversión sin pago, devolución ni movimiento financiero.$texto$,$texto$Este ejemplo no prueba una condonación con abonos previos. En ese escenario sólo se reactiva el saldo condonado y se conservan los abonos; queda para otra prueba humana.$texto$,$texto$/admin/convenios-pago$texto$)
) v(slug,numero,titulo,perfil,modulo,instrucciones,ejemplo,resultado,precaucion,ruta) ON g.slug=v.slug;

-- Homologar referencias pendientes en la guía anterior sin alterar migraciones aplicadas.
UPDATE guia_proceso_paso SET precaucion=replace(precaucion,
 $texto$La cancelación de esta condonación es otro escenario todavía pendiente de prueba humana.$texto$,
 $texto$La cancelación tiene su propia guía confirmada: Cancelar una condonación total: recuperar el adeudo de $500.$texto$)
WHERE guia_id=(SELECT id FROM guia_proceso WHERE slug='convenio-condonacion-total-500') AND numero=8;
UPDATE guia_proceso_paso SET precaucion=$texto$La cancelación del acuerdo se documenta en su propia guía confirmada; no forma parte del cierre de esta prueba de condonación.$texto$
WHERE guia_id=(SELECT id FROM guia_proceso WHERE slug='convenio-condonacion-total-500') AND numero=9;
UPDATE guia_proceso SET version_contenido=version_contenido+1,revisada_el=DATE '2026-10-08'
WHERE slug='convenio-condonacion-total-500';
