CREATE TABLE acuerdo_anticipado (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 institucion_id BIGINT NOT NULL REFERENCES institucion(id), plantel_id BIGINT NOT NULL REFERENCES plantel(id),
 tutor_id BIGINT NOT NULL REFERENCES tutor(id), folio VARCHAR(40) NOT NULL UNIQUE,
 fecha_limite DATE NOT NULL, politica_beca VARCHAR(15) NOT NULL CHECK(politica_beca IN ('CONSERVAR','SUSTITUIR')),
 tipo_beneficio VARCHAR(15) NOT NULL CHECK(tipo_beneficio IN ('MENSUALIDAD','PORCENTAJE','MONTO')),
 valor_beneficio NUMERIC(16,4), cargo_bonificado_id BIGINT REFERENCES cargo(id),
 CHECK ((tipo_beneficio='MENSUALIDAD' AND cargo_bonificado_id IS NOT NULL) OR (tipo_beneficio IN ('PORCENTAJE','MONTO') AND valor_beneficio IS NOT NULL AND valor_beneficio>0 AND (tipo_beneficio<>'PORCENTAJE' OR valor_beneficio<=100))),
 motivo VARCHAR(2000) NOT NULL CHECK(btrim(motivo)<>''), moneda VARCHAR(3) NOT NULL,
 total_base NUMERIC(14,2) NOT NULL CHECK(total_base>0), total_beneficio NUMERIC(14,2) NOT NULL CHECK(total_beneficio>0),
 total_pagar NUMERIC(14,2) NOT NULL CHECK(total_pagar>0 AND total_pagar=total_base-total_beneficio),
 autorizado_por_id BIGINT NOT NULL REFERENCES usuario(id), estado VARCHAR(15) NOT NULL DEFAULT 'PROPUESTO' CHECK(estado IN ('PROPUESTO','APLICADO','CANCELADO')),
 aplicado_en TIMESTAMPTZ, cancelado_en TIMESTAMPTZ, motivo_cancelacion VARCHAR(2000),
 creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, creado_por_id BIGINT,
 actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, actualizado_por_id BIGINT, version BIGINT NOT NULL DEFAULT 0
);
CREATE SEQUENCE acuerdo_anticipado_folio_seq;
CREATE TABLE acuerdo_anticipado_cargo (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, acuerdo_id BIGINT NOT NULL REFERENCES acuerdo_anticipado(id),
 cargo_id BIGINT NOT NULL REFERENCES cargo(id), activo BOOLEAN NOT NULL DEFAULT TRUE,
 original NUMERIC(14,2) NOT NULL, total_actual NUMERIC(14,2) NOT NULL, beca NUMERIC(14,2) NOT NULL CHECK(beca>=0),
 base NUMERIC(14,2) NOT NULL CHECK(base>0), beneficio NUMERIC(14,2) NOT NULL CHECK(beneficio>=0 AND beneficio<=base),
 pagar NUMERIC(14,2) NOT NULL CHECK(pagar>=0 AND pagar=base-beneficio),
 creado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, creado_por_id BIGINT,
 actualizado_en TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, actualizado_por_id BIGINT, version BIGINT NOT NULL DEFAULT 0,
 UNIQUE(acuerdo_id,cargo_id)
);
CREATE UNIQUE INDEX ux_anticipo_cargo_activo ON acuerdo_anticipado_cargo(cargo_id) WHERE activo;
CREATE INDEX ix_anticipo_listado ON acuerdo_anticipado(institucion_id,plantel_id,id);
ALTER TABLE pago ADD COLUMN acuerdo_anticipado_id BIGINT REFERENCES acuerdo_anticipado(id);
CREATE UNIQUE INDEX ux_anticipo_pago_pendiente ON pago(acuerdo_anticipado_id) WHERE acuerdo_anticipado_id IS NOT NULL AND estado IN ('PENDIENTE_VALIDACION','VALIDADO');
ALTER TABLE ajuste_cargo ADD COLUMN acuerdo_anticipado_id BIGINT REFERENCES acuerdo_anticipado(id);
CREATE INDEX ix_anticipo_ajustes ON ajuste_cargo(acuerdo_anticipado_id,id);
