CREATE TABLE archivo (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    institucion_id        BIGINT NOT NULL REFERENCES institucion(id),
    clave_almacenamiento  VARCHAR(500) NOT NULL,
    nombre_original       VARCHAR(255) NOT NULL,
    tipo_mime             VARCHAR(100) NOT NULL,
    tamano_bytes          BIGINT NOT NULL,
    checksum_sha256       VARCHAR(64) NOT NULL,
    estado                VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id         BIGINT,
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id    BIGINT,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_archivo_clave UNIQUE (clave_almacenamiento),
    CONSTRAINT ck_archivo_nombre CHECK (btrim(nombre_original) <> ''),
    CONSTRAINT ck_archivo_mime CHECK (btrim(tipo_mime) <> ''),
    CONSTRAINT ck_archivo_tamano CHECK (tamano_bytes > 0),
    CONSTRAINT ck_archivo_checksum CHECK (checksum_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_archivo_estado CHECK (estado IN ('DISPONIBLE', 'BLOQUEADO', 'RETIRADO')),
    CONSTRAINT ck_archivo_version CHECK (version >= 0)
);

ALTER TABLE alumno
    ADD COLUMN fotografia_archivo_id BIGINT REFERENCES archivo(id);

CREATE TABLE alumno_fotografia (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id             BIGINT NOT NULL REFERENCES alumno(id),
    archivo_id            BIGINT NOT NULL REFERENCES archivo(id),
    retirada_en           TIMESTAMPTZ,
    creado_en             TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    creado_por_id         BIGINT,
    actualizado_en        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por_id    BIGINT,
    version               BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ux_alumno_fotografia_archivo UNIQUE (archivo_id),
    CONSTRAINT ck_alumno_fotografia_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX ux_alumno_fotografia_actual
    ON alumno_fotografia (alumno_id) WHERE retirada_en IS NULL;
CREATE INDEX ix_archivo_institucion_estado
    ON archivo (institucion_id, estado);
CREATE INDEX ix_alumno_fotografia_historial
    ON alumno_fotografia (alumno_id, creado_en DESC);
