package escuela.auditoria.entity;

public enum AccionAuditoria {
    PAGO_VALIDADO,
    PAGO_RECHAZADO,
    PAGO_CANCELADO,
    DEVOLUCION_EJECUTADA,
    TRANSFERENCIA_APLICADA,
    RETIRO_FONDO_EJECUTADO,
    MOVIMIENTO_REVERTIDO,
    TRANSFERENCIA_REVERTIDA,
    PERMISO_ROL_ASIGNADO,
    ROL_USUARIO_ASIGNADO,
    ROL_USUARIO_RETIRADO,
    EVENTO_PUBLICADO,
    EVENTO_CANCELADO,
    AVISO_PUBLICADO,
    AVISO_RETIRADO,
    PORTAL_TUTOR_SOPORTE
}
